### ISSUE TITLE
verify_recaptcha returns true even if I enter the wrong text (Rails 4)

### ISSUE THREAD

**Issue by houmanka** [ambethia/recaptcha#106]
It is strange, even if I enter the wrong text in the recaptcha I get the true result.
Do I need to add anything to the Strong Params in the controller? 
At user controller:
`@user = User.new(user_params)
if verify_recaptcha( :model => @user, :message => t('incorrect_captcha') ) && @user.save
end
`
User params:
`private
  def user_params
    params.require(:user).permit(:name, :email, :password, :salt, :encrypted_password, :mobile, :password_confirmation,  :remember_token, :role_ids, :password_confirmation, :salt, :encrypted_password, :home_phone, :golflinknumber, :first_name, :last_name, :dob, :current_password)
  end
`

**Comment by marceloboeira** [comment]
@houmanka you don't need to allow the strong params, can you post your Gemfile/Gemfile.lock, or specify the Rails version ?


PS: I'm using Rails 4.2 and  its working fine!
