### ISSUE TITLE
Proposal for modified API

### ISSUE THREAD

**Issue by dyba** [ambethia/recaptcha#108]
I started using this library and I was wondering what others think about modifying the API. Rather than include ```Recaptcha::Verify```, I thought perhaps ```Recaptcha``` could have a class method ```verify```. When I use this library in my controller, I want to be able to do the following:

``` ruby
Recaptcha.verify

# rather than

include Recaptcha::Verify # This is done automatically and I have no control over it :/
```

What are the community's thoughts about modifying the API as I propose?

**Comment by grosser** [comment]
give it a try ... I'm a little afraid you won't have request information ...
travis works now ...
