### ISSUE TITLE
New API v2 in Preview?

### ISSUE THREAD

**Issue by homezada** [ambethia/recaptcha#112]
I think there is a V2 API in preview from Google? Any plans to support that?

http://www.google.com/recaptcha/api2/demo

**Comment by nguyenchiencong** [comment]
+1

**Comment by userium** [comment]
+1

**Comment by korin** [comment]
:+1:

**Comment by funkdified** [comment]
Important to add the following to the initializer:
```
Recaptcha.configure do |config|
  config.api_version = 'v2'
end
```

**Comment by funkdified** [comment]
No I am seeing

```
/home/funkdified/rails_projects/hearingtracker/config/initializers/recaptcha.rb:4:in `block in <top (required)>': undefined method `api_version=' for #<Recaptcha::Configuration:0x000000065c9a58> (NoMethodError)
```

**Comment by korin** [comment]
please realease 0.3.7 with api v2 support

**Comment by ambethia** [comment]
I haven't had a chance to work on the tests yet. Pull requests are always welcome ;)

**Comment by saidie** [comment]
:+1:

**Comment by Bmorrical** [comment]
When I try to use the gem, I can't run rake or precomile tasks.  I receive the notice:  

git://github.com/abethia/recapcha.git (at master) is not yet checked out.  Run 'bundle install' first.

I doesn't matter how many times I run bundle install or bundle update I still get the same failure.

Suggestions?

**Comment by xelwarto** [comment]
+1 => release for v2 API

**Comment by Tailzip** [comment]
+1

**Comment by stevenyap** [comment]
+1

**Comment by austinrfnd** [comment]
hi @ambethia any time to push out a new version?  I added a pull request (https://github.com/ambethia/recaptcha/pull/119) for some v2 / v1 tests.  My company and I are very interested in v2 of using recaptcha and if I need to modify or add to my pull request I definitely can.  Please let me know if there is anything I can do to help.

**Comment by ambethia** [comment]
Released, thanks everyone who bugged me to push this.

**Comment by enorziana** [comment]
Many thanks @ambethia :)

**Comment by Bmorrical** [comment]
Many thanks, ++

**Comment by funkdified** [comment]
Woo
