### ISSUE TITLE
The gem is not updated on Rubygems, so no v2 support if you download from there

### ISSUE THREAD

**Issue by plicjo** [ambethia/recaptcha#117]
The `config.api_version = 'v2'` line doesn't work when you download the gem from **rubygems.org**.

I figure that 0.3.6 source code here on Github is different from the one at rubygems.org.
Can you push up the updated Github version to RubyGems?

**Comment by ambethia** [comment]
See #112. As soon as I can get test coverage or someone submits a good pull request with it, I will push a new release.
