### ISSUE TITLE
ERROR: Invalid domain for site key

### ISSUE THREAD

**Issue by qaswm** [ambethia/recaptcha#122]
Hi,

Am trying to use a gem for a site and have followed all the suggestions to build the site.

The reCaptcha shows on localhost but when deployed to production I only get "ERROR: Invalid domain for site key"

Not sure what do I need to do here. http://bit.ly/1EajuIk

**Comment by qaswm** [comment]
The version of the Gem that i am using is recaptcha (0.3.6) and the config file is: 

Recaptcha.configure do |config|
  config.public_key  = '6Lc6BAAAAAAAAChqRbQZcn_yyyyyyyyyyyyyyyyy'
  config.private_key = '6Lc6BAAAAAAAAKN3DRm6VA_xxxxxxxxxxxxxxxxx'
  # Uncomment the following line if you are using a proxy server:
  # config.proxy = 'http://myproxy.com.au:8080'
  # Uncomment if you want to use the newer version of the API,
  # only works for versions >= 0.3.7:
  # config.api_version = 'v2'
end

**Comment by austinrfnd** [comment]
I came across this as well we had to generate new keys for v2 if you are switching from v1.

**Comment by mcamara** [comment]
You have to add your url on the recaptcha admin menu

**Comment by 4thking** [comment]
I was having the same issue and after running "gem install recaptcha" again it cleared it right up.  Might be worth a try?

**Comment by Reyzapermanasaputra** [comment]
for localhost please regist with label : "local" Domains "localhost" Owners "your email" in google.com/recaptcha/admin#list and get your site key and secretkey

config/recaptca.rb

Recaptcha.configure do |config|

config.public_key = '6LcauA8TAAAAAGncDdV2pjc8lxWHf7oSiMz9_0OS' << your site key
config.private_key = '6LcauA8TAAAAAJi52ztlkgdTQl9rSO8Y_haSONzO' << your secret key
end

and following tutorial https://github.com/ambethia/recaptcha/

**Comment by sukhwindersingh7** [comment]
Try this:
Paste this snippet before the closing </head> tag on your HTML template:
<script src='https://www.google.com/recaptcha/api.js'></script>
