### ISSUE TITLE
Problems with timeout

### ISSUE THREAD

**Issue by mcamara** [ambethia/recaptcha#123]
Hi there,

I'm having problems with this plugin, used like the examples says:
```ruby
    if verify_recaptcha({:model => @applicant}) && @applicant.save
```
it makes a timeout error as my network speed is not really fast. Trying to solve it as the documentation says, like this: (I've changed the timeout time)
```ruby
    if verify_recaptcha({:timeout => 60, :model => @applicant}) && @applicant.save
````
makes a RecaptchaError like the following one:
```
Recaptcha::RecaptchaError in ApplicantsController#create
end of file reached
```

Do you know what I am doing wrong? I've tried changing the proxy on the configuration file and I'm still struggling with it.

Thanks!

**Comment by grosser** [comment]
no idea... try opening the gem and add a few debug statements or remove the rescue statements ... then we might get a nice backtrace
