### ISSUE TITLE
 Recaptcha::RecaptchaError: No live threads left. Deadlock? 

### ISSUE THREAD

**Issue by olivierlacan** [ambethia/recaptcha#127]
Whenever debugging recaptcha with Pry I can't call `verify_recaptcha` within a pry session without causing this exception: ` Recaptcha::RecaptchaError: No live threads left. Deadlock?`.

I doubt there's a simple way to get around this but I wanted to document it for people facing the same issue. Feel free to close this. :-)

**Comment by fenec** [comment]
What setup do you have?

**Comment by grosser** [comment]
solved by #131
