### ISSUE TITLE
Have you seen Rails3 issues with the latest version (0.4.0)?

### ISSUE THREAD

**Issue by bunnymatic** [ambethia/recaptcha#135]
Hi

I just recently upgraded recaptcha on an old Rails3 app and it seems to be working just fine.  I wonder if there are known issues, or if you've dropped support (as it says in the readme) simply because it's too much work to support the old stuff.

Thanks, in advance
jon

**Comment by ambethia** [comment]
It’s not “officially” “supported”, but it should still work fine. It’s just that if changes are made that prevent it from working, I probably won’t back port them. I don’t know of any issues though.


—
Jason L Perry

**Comment by bunnymatic** [comment]
Great.  thanks for the info.
