### ISSUE TITLE
ERROR: Stoken expired issue in production

### ISSUE THREAD

**Issue by spartan1234** [ambethia/recaptcha#137]
This works fine on local-host environment, both in development and production, but when I am using this on VM(Azure VM), it gives **ERROR: Stoken Expired issue.**

Screenshot of the issue http://imgur.com/pFfJXRn

recaptcha version - 0.4.0
Rails version 4.2.1
Passenger Phusion server(5.0)

On VM(Ubuntu 14.10), rails application runs on localhost(port:3000) and all external request on server(HTTP) are redirected to local-host.

**Comment by guilleart** [comment]
Having this issue as well, using:
Rails 3.2.21
Passenger 5.0.1 on Apache2

A little more context:
I've been using the 0.3.5 version fo the gem with the v1 recaptcha and I want to upgrade to V2:
Updated to version 0.4.0, generated new keys for the domain and added the following to the `config` block:
```
  config.api_version = 'v2'
```

Is it ok if I test this from a local environment without an accessible public IP?
Do I need to do something else?

**Comment by spartan1234** [comment]
Testing from local environment won't give any issue.
Btw, create one file (e.g recaptcha.rb) in initializers folder and add the following code

Recaptcha.configure do |config|
  config.public_key  = "PublicKey"
  config.private_key = "PrivateKey"
  config.api_version = 'v2'
end

**Comment by guilleart** [comment]
Yup! Already have it like that :)
```
Recaptcha.configure do |config|
  config.public_key  = RECAPTCHA[:public_key]
  config.private_key = RECAPTCHA[:private_key]
  config.api_version = 'v2'
end
```

Is there a way to indicate the gem not to use the s-token?

**Comment by spartan1234** [comment]
I am still struggling to figure out the reason for this error and what is the meaning of SToken :(
SToken seems like Security token (blind guess), but why this error is coming when using it with public accessible IP.

**Comment by spartan1234** [comment]
Does anyone have an idea why this issue is occurring ?

**Comment by brendon** [comment]
Hi there, this was something I added in: https://github.com/ambethia/recaptcha/pull/132

My first guess is that the clock on your production machine might not be in sync? In that pull request and in the referenced issue #130 you'll see the rationale behind the stoken.

Part of the process is that we need to generate a timestamp: `'ts_ms' => (Time.now.to_f * 1000).to_i` that is then combined with some other stuff and encrypted and sent to google. Google uses the timestamp to ensure the stoken isn't too old (i.e. intercepted and reused).

I'd be interested to see how you get on with solving this.

**Comment by brendon** [comment]
Also, I'm confused why you're getting this error at all since the latest gem release doesn't contain this change yet.

**Comment by spartan1234** [comment]
I checked date-time for my machine, PostgreSQL and rails. All are in sync and correct.

**Comment by spartan1234** [comment]
Hi Brendon,
After going through your comments I checked date-time on my environment for PostgreSQL, Machine and Rails. All were in sync and were correct.
As you mentioned that u didn't included this in latest gem, a bell rang in my head and I went and checked my Gemfile. 
I was using 
gem "recaptcha", require: "recaptcha/rails", github: "ambethia/recaptcha"  - basically this is using GitHub code to build gem instead of using latest gem i.e. gem 'recaptcha', '~> 0.4.0'
Hence, I copied "gem 'recaptcha', '~> 0.4.0' " in my Gemfile and it started working.

Why I was using gem "recaptcha", require: "recaptcha/rails", github: "ambethia/recaptcha"
This is the top answer while using google. btw, I will refer this issue on stackoverflow answer.

Thanks a lot :)

**Comment by brendon** [comment]
That's very interesting! It'd still be good to know if the stoken stuff causes problems though. It just requires that you add at least one domain to your list against your key in their configuration panel.

Because you're getting the expired message, it means that everything is getting encrypted properly. Perhaps `(Time.now.to_f * 1000).to_i` is returning something incorrect? Are time zones being invoked through this for instance. Anyway, if you manage to find any clues, please let me know :)

**Comment by abhinaykumar** [comment]
issue is still there, even for the latest version of Gem. 
![screen shot 2016-02-01 at 8 39 04 pm](https://cloud.githubusercontent.com/assets/4496810/12721077/e49412d2-c923-11e5-99ff-278ff44a98e9.png)

**Comment by brendon** [comment]
Hi @abhinaykumar, did you take a look at my previous comment about what is being generated by `(Time.now.to_f * 1000).to_i`? Perhaps there is a time-drift in your system? Or perhaps some interference causing that to generate a time in a particular zone instead of UTC?

**Comment by abhinaykumar** [comment]
@brendon Yeah thats true, updating the server time solved the issue. thanks for the response :)

**Comment by brendon** [comment]
Thanks @abhinaykumar :) Glad to know it worked.

**Comment by jlroettger** [comment]
I experienced the same issue on my dev machine, changing `(Time.now.to_f * 1000).to_i` to `(Time.now.utc.to_f * 1000).to_i` fixed the issue.

**Comment by grosser** [comment]
anything that can be changed in the library / want to make a PR ?

**Comment by jlroettger** [comment]
Yeah I'll submit a PR once I've verified it's still working in other environments. My encounter with this error might just be the edge case of weirdos like me working on Windows (RailsInstaller)

**Comment by grosser** [comment]
Oh god, stop doing that :D

**Comment by brendon** [comment]
Lol, that bring back memories of my early years with Rails and Windows. Bought a MacBook Pro in 2009 and never looked back! Still using the same laptop even!

`Time.now.utc.to_f` and `Time.now.to_f` should return the same thing given `to_f` returns seconds since the epoch in UTC if I'm not mistaken?

**Comment by jlroettger** [comment]
Hm, yeah you're right, if `to_f` returns a UTC-based value there shouldn't be a difference. I'll take a look again tonight, it was definitely not working for me until I made the change but maybe there was something else going on.

**Comment by jlroettger** [comment]
So I finally got a chance to take another look. While the recaptcha did work after changing `Time.now.to_f` to `Time.now.utc.to_f`, that was not the fix. I was actually getting the error randomly on ~75% of all refreshes, and I guess I must have just won the lotto with a few refreshes after making the change.

The real problem was with my local clock, as others had experienced. As I mentioned before, I sometimes work on a Windows machine; I switched my clock to sync with `time.nist.gov` instead of the default `time.windows.com` and the error has stopped showing up.

**Comment by brendon** [comment]
Thanks @jlroettger, I think what I'll do is outline the requirement for a precise clock in the documentation and do a PR. It seems to have tripped a few people up now.

**Comment by MoezGholami** [comment]
@abhinaykumar Thanks, I resolved my error by using `ntp` to sync my server time.

**Comment by brendon** [comment]
Good to hear :)

**Comment by shrirambalakrishnan** [comment]
Hi everyone,

Am looking hard to debug this error. In my case, the time zone is configured to use 'UTC' in application.rb file.

`config.time_zone = 'UTC'`

In this case, will the time in server machine be an issue?

**Comment by brendon** [comment]
Hi @shrirambalakrishnan :) That shouldn't cause you any problems. The only problem will be if the time on your machine is actually incorrect (in UTC), or incorrect in your timezone.

We grab UTC time and convert it to an integer to supply to recaptcha.

**Comment by shrirambalakrishnan** [comment]
Hi @brendon, thanks for your prompt reply. Updating server time solved it. Previously the time difference was just around 1 minute and was not working because of that.

Synced the server time with ntp and it worked.

Thank you @brendon.

**Comment by brendon** [comment]
Glad to hear it @shrirambalakrishnan :) I'm glad this issue post is helping people :)

**Comment by junket** [comment]
Hi @brendon, I have user reports of seeing this error in production on an app deployed to Heroku. Any ideas of how I can troubleshoot/fix there?

Thanks for any light you can shed.

**Comment by brendon** [comment]
Hi @junket, yes that's a tough one. It's almost certainly going to be an incorrect time on the server serving the request. Unfortunately I don't know how their setup works in terms of wether your application is running on just one server etc... and how you'd figure out which server has the time lag.

Best to get in touch with Heroku and point them to this issue to see if they can have a look at their end. :)

**Comment by junket** [comment]
Okay, thanks @brendon. Will report back if I learn anything.

**Comment by jlroettger** [comment]
@junket - if you don't need it you can always disable the security token with stoken: false

**Comment by brendon** [comment]
Good point @jlroettger :)

**Comment by junket** [comment]
Thanks @jlroettger! Good point. I do need the functionality that secure token enables (one API key across lots of domains that are regularly being added to) but I didn't realize that using the secure token is now deprecated by Recaptcha: https://developers.google.com/recaptcha/docs/secure_token

So I evolved our implementation to use domain validation, and this gem has been nicely updated to accommodate that:  I pass a validation proc to verify_recaptcha to validate the hostname internally. So far, so good. Thanks!

**Comment by grosser** [comment]
Hmmm so we use a deprecated option by default :(
Want to make a PR to make domain validation the new default ?
... something like do not use stoken and then raise when domain validation
is not configured ?

On Thu, Apr 14, 2016 at 4:58 AM, Junket Design Co. <notifications@github.com

**Comment by brendon** [comment]
Lol, this is the first I'd heard of the deprecation. Yes we should deprecate it also and implement the other solution.

**Comment by jvvlee** [comment]
@junket Can you clarify what you did? Syncing time on our servers only partially resolves this error.

**Comment by junket** [comment]
Sorry @jvvlee, just saw this. Here's what I did:  After creating an internal hostname validation function like `is_host_valid?` I then passed it to verify recaptcha like:

`validator = Proc.new {|hostname| is_host_valid?(hostname) }`
`verify_recaptcha(:hostname => validator)`

I may be screwing up, and I'm sure it could be improved. But it solved my problem. Of course, you also have to turn off Recaptcha's domain validation as described here:  https://developers.google.com/recaptcha/docs/domain_validation

**Comment by brendon** [comment]
Ok, so they sent out an email today saying that stoken will be removed on 18 May! Pretty short notice given I don't recall receiving an email about the deprecation in the first place :)

@junket, that looks like a good solution to me.

We should probably at least turn off the stoken by default, and then probably remove it after 18 May given it won't work anyway.

**Comment by brendon** [comment]
https://github.com/ambethia/recaptcha/issues/179

**Comment by Mathieu44** [comment]
Have you try to regenerate the captcha key ? It's work fine for me... :)

**Comment by AlexandrBasan** [comment]
Had the same problem on local machine (macOS), changed Time Synchronization server in Date & Time Preference Settings

**Comment by brendon** [comment]
@AlexandrBasan, you shouldn't be using this method anymore, see: https://github.com/ambethia/recaptcha/issues/179 :)

**Comment by sjayanna** [comment]
Updating the gem did the trick for me using command `bundle update recaptcha` at `RAILS_ROOT`
