### ISSUE TITLE
expired_callback doesn't working

### ISSUE THREAD

**Issue by ryush00** [ambethia/recaptcha#138]
![image](https://cloud.githubusercontent.com/assets/4997174/8920948/02e18ff6-350b-11e5-9499-f8cfd5229d94.png)

![image](https://cloud.githubusercontent.com/assets/4997174/8920962/129299fe-350b-11e5-9366-471085fb2a6b.png)

    = recaptcha_tags(:callback => 'new_vote_recaptcha', :expired_callback => 'new_vote_recaptcha_expired')

I used this code, but it wasn't applied.

**Comment by grosser** [comment]
dig into the gem and find out why ... if it's a bug, please open a PR
