### ISSUE TITLE
release new version

### ISSUE THREAD

**Issue by kintner** [ambethia/recaptcha#140]
Can we get a new version released? Thanks!

**Comment by grosser** [comment]
@ambethia

**Comment by astuyve** [comment]
Also like to :+1: this. It'd be nice to get the token code released.

**Comment by ambethia** [comment]
Sorry for the long delays everyone. @grosser has volunteered to help with releases, so I'm setting that up. Thanks!

**Comment by grosser** [comment]
0.5.0 is out
