### ISSUE TITLE
ERROR: Stoken expired

### ISSUE THREAD

**Issue by fatehwaharp** [ambethia/recaptcha#149]
I've just follow the readme, 
```
gem "recaptcha", require: "recaptcha/rails"
```

on the development side, everything was okay,
but when I push it to production it appears to be "ERROR: Stoken expired"

**Comment by grosser** [comment]
I only saw that once when I when back to a cached page ... did you maybe cache the captcha ?

**Comment by fatehwaharp** [comment]
I guess i didnt cache the captcha, Btw how to check if i cache it or not ?

On Wed, Dec 9, 2015 at 11:19 AM, ambethia/recaptcha
<reply@reply.github.com>
wrote:
I only saw that once when I when back to a cached page ... did you maybe cache
the captcha ?

—
Reply to this email directly or view it on GitHub
[https://github.com/ambethia/recaptcha/issues/149#issuecomment-163092813] .[https://github.com/notifications/beacon/AASu0uDPkNPORREJMdnb3Y1kAn7iLrbbks5pN5VOgaJpZM4Gxjn9.gif]

**Comment by grosser** [comment]
if you have a `<% cache 'foo' do %>` around it ... possibly inspect the page and see if stoken changes in the html

**Comment by fatehwaharp** [comment]
yeah the stoken change

**Comment by grosser** [comment]
and you still get this error on the first submission ?
and it works with the previous version ? (you did not use v1, right ?)

**Comment by fatehwaharp** [comment]
yeah still got the same error,
I'm using 1.0.2

**Comment by grosser** [comment]
can you try the rails or sinatra demo with your keys and see if you get the same error ?

**Comment by grosser** [comment]
demo directory in the repo

**Comment by fatehwaharp** [comment]
yeah already tried that, in development everything seems fine

**Comment by grosser** [comment]
great :(

but the token changes in production too ?
maybe boot with RAILS_ENV=production to reproduce ?

**Comment by fatehwaharp** [comment]
yeah the stoken key change everytime the page refresh

**Comment by grosser** [comment]
yeah idk ... afaik nothing changed around the verification behavior ...
just moved around :(

try reproducing locally with production env and see what commit / version
breaks it ... maybe try demo with production env first for simplicty ...
using the production locally also works ?

**Comment by fatehwaharp** [comment]
I didnt try to run it on production locally, 

Nvm, as for now I'm jus gonna stick with version 0.4.0, since it was the only version available that is working for me,

Thanks for the help man.

**Comment by grosser** [comment]
hope nobody else runs into this ... no idea why that would be happening :(

**Comment by matthias-g** [comment]
I experienced the same issue and found that the system clock on the production machine was out of sync.
