### ISSUE TITLE
Ruby version

### ISSUE THREAD

**Issue by pavelvasev** [ambethia/recaptcha#150]
Why do you require ruby version 2.0 in gemspec? The code of your gem seems to be 1.8 friendly, isn't it?

**Comment by grosser** [comment]
Using a few keyword args + new hash style ... maybe other things.
1.8/9 are dead and no longer get security updates, so nobody should be
running them ... and if you do then updating recaptcha is not the top
priority ... or are you maintaining a gem that needs recaptcha ?

**Comment by pavelvasev** [comment]
OK i see you have few api calls that std lib of ruby 1.8 doesn't have.
BTW I didn't found any new hash style uses, which is good for me.:)

p.s. I maintain a project which is very huge and made for rails 2.x / ruby 1.8. 
Thank you for your vision about ruby 1.8/9!

**Comment by grosser** [comment]
Oh boy ... rails2/1.8 ... good luck with that!
