### ISSUE TITLE
Catching Exception instead of StandardError

### ISSUE THREAD

**Issue by sringling** [ambethia/recaptcha#152]
At the end of verify_recaptcha:

rescue Exception => e
        raise RecaptchaError, e.message, e.backtrace

To my understanding we almost never want to do this.  https://robots.thoughtbot.com/rescue-standarderror-not-exception explains this.

I ran into a case where we got a strange Recaptcha::RecaptchaError, just once ever, and it seems it must have been some kind of resource or OS-related failure that I'd rather have seen the root cause of.

The message was "Recaptcha::RecaptchaError: exception object expected" and the trace has timeout.rb in there so I'm guessing it was a network timeout.

**Comment by grosser** [comment]
yeah ... not a fan of this ... rescuing StandardError would be better ...
can you make a PR for that ?

alternatively only rescue known things ... like network errors etc instead of everything ...

**Comment by sringling** [comment]
It looks like you did this recently on November 18th!

https://github.com/ambethia/recaptcha/commit/fc599d3e8a9b6bb9fb29d0925fbfb72f9db2afdb

Thanks!  This is a great gem - 2 lines for recaptcha validation.

**Comment by grosser** [comment]
Hehe, glad it's not another bug :D
