### ISSUE TITLE
Multiple Widget Fails Verify

### ISSUE THREAD

**Issue by epochslee** [ambethia/recaptcha#154]
I'm trying to implement this gem using the multi-widget instructions. I'm able to get two widgets to show which does check off the "i'm not a robot" checkbox. But when submitting, the verify_recaptcha never passes.

Works fine when only use one widget by using the <%= recaptcha_tags %>.

**Comment by grosser** [comment]
pushed a multi demo ... works fine for me ... `cd demo/rails + rails s`

**Comment by batbayar-su** [comment]
Tested demo on my code and it working great. Thanks
