### ISSUE TITLE
testing environment

### ISSUE THREAD

**Issue by fivepapertigers** [ambethia/recaptcha#155]
Hey, I'm building an app on Sinatra and testing with RSpec. Your skip_verify_env only checks against the  RAILS_ENV environment variable, but Sinatra uses RACK_ENV, so the verify_recaptcha helper returns false in my test env.

Not a big deal, I'm just setting RAILS_ENV in my test mode to accommodate (a little hackish but whatever), but just wanted to give you a heads up.

**Comment by grosser** [comment]
can you make a PR to check both ?

**Comment by fivepapertigers** [comment]
Sure, will do.
