### ISSUE TITLE
How to pass options (url vars) when loading api.js

### ISSUE THREAD

**Issue by bosskovic** [ambethia/recaptcha#160]
How do I load api.js with some options, for example language settings?

If I just add this 
`= javascript_include_tag 'https://www.google.com/recaptcha/api.js?hl=it'`
to `<head>` it works fine, but there is a javascript error:

> ReCAPTCHA placeholder element must be empty

I can see the server being set [here](https://github.com/ambethia/recaptcha/blob/master/lib/recaptcha.rb#L9), but I can not see a way to pass any options. Is this presently supported?

Let me just add that doing [this](http://stackoverflow.com/a/31828175/2803062) (specifying options in `RecaptchaOptions` in the head) does not work

**Comment by bosskovic** [comment]
For anyone looking for it, the solution is to pass hl when calling recaptcha_tags, like this:

```= recaptcha_tags hl: 'it'```

**Comment by dwaynemac** [comment]
this is not working for me. :hl parameter is ignored by recaptcha_tags

**Comment by grosser** [comment]
looks like it should work according to https://github.com/ambethia/recaptcha/blob/master/lib/recaptcha/client_helper.rb#L64-L68

are you on latest ? can you paste the html it generates ? can you reproduce in the demo folder ?
