### ISSUE TITLE
Rails 2.3.18 support.

### ISSUE THREAD

**Issue by collegeimprovements** [ambethia/recaptcha#161]
I know it may not be possible to provide support for all Rails versions.
But is there any version of the recaptcha gem that can work with rails2.3 ?

Thanks for creating this wonderful gem.

**Comment by grosser** [comment]
0.4 might work ... otherwise 3.0 ...or fork it and fix the issues you run into ...

**Comment by collegeimprovements** [comment]
Okay. Thanks for the quick reply.
