### ISSUE TITLE
recaptcha mobile resizing

### ISSUE THREAD

**Issue by acegilz** [ambethia/recaptcha#162]
I have this problem:
https://www.geekgoddess.com/how-to-resize-the-google-nocaptcha-recaptcha/

How do I fix it with this gem?

**Comment by grosser** [comment]
use css to do it ... possibly `important!` ?

**Comment by acegilz** [comment]
any example or link?

**Comment by acegilz** [comment]
alright this is it.

```
                    <% if !browser.device.mobile? %>
                        <%= recaptcha_tags size: 'compact' %>
                    <%else%>
                        <%= recaptcha_tags %>
                    <%end%>
```

**Comment by grosser** [comment]
FYI this should also work then: `recaptcha_tags size: (browser.device.mobile? ? 'compact' : nil)`
