### ISSUE TITLE
Error parsing header X-XSS-Protection

### ISSUE THREAD

**Issue by j3ck** [ambethia/recaptcha#163]
Hello.
I use this gem and i have some issues after update http to https on production server.
views:
= recaptcha_tags(ssl: true)
browser console provide this errors:
http://i.imgur.com/IcXzlpa.png
source error line:
http://i.imgur.com/8LlXCAS.png

Someone can help me ?

**Comment by grosser** [comment]
smells like the way it adds scripts is blocked ... can you try changing that to a normal scrip tag with async and see if the error goes away ?

**Comment by j3ck** [comment]
@grosser   Think i can't change it
http://i.imgur.com/gjDnOVq.png

**Comment by grosser** [comment]
bundle show recaptcha and edit it ...
or did you men to say "even with the proper script tag it shows the
warning" ?

**Comment by j3ck** [comment]
@grosser thanks for answers,  i have duplicated x-xss-protection header in the nginx conf, fixed.

**Comment by grosser** [comment]
glad to hear it's not something weird in recaptcha :D
