### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by dougharman** [ambethia/recaptcha#165]
Demo is for recaptcha version 1, not 2.  
Also doesn't conform to secrets.yml format, i.e., 
recaptcha_secret_key: Rails.application.secrets.recaptcha_secret_key

**Comment by grosser** [comment]
secrets.yml does not conform to 12-factor ... so it uses dot-env ... but does not really matter how it's gotten ... demo runs recaptcha v2 (only v2 is supported now / it is version 2 by default)

<img width="345" alt="screen shot 2016-03-20 at 7 01 09 pm" src="https://cloud.githubusercontent.com/assets/11367/13909328/24413480-eece-11e5-9357-9a5871e2b288.png">

**Comment by dougharman** [comment]
Got it!  Thanks, Doug

 

________________________________
