### ISSUE TITLE
Make reCaptcha API response available to be possible to check domain manually

### ISSUE THREAD

**Issue by talyssonoc** [ambethia/recaptcha#167]
Currently there's a way to check the domain name where the validation directly from the server instead of using configuration in reCaptcha dashboard (https://developers.google.com/recaptcha/docs/domain_validation).

It can be done using the API response from Google reCaptcha (https://developers.google.com/recaptcha/docs/verify#api-response), however there's no way to access the API response using this gem, would it be possible to include some way to access that response (https://github.com/ambethia/recaptcha/blob/master/lib/recaptcha/verify.rb#L26)?

**Comment by grosser** [comment]
so I assume you have a key that is not tied to a certain domain ... how
about changing that ? :)

alternatively:
 - how about returning the reply instead of true ?
 - how about passing in `domain: xxx` and then make recaptcha gem validate
it ?

**Comment by talyssonoc** [comment]
I have a key that I need to use in a lot of domains in a multitenant application, that's why I can't tie the key to a certain domain.

I like the second option of passing the domain, since it wouldn't be a breaking change, right?

**Comment by grosser** [comment]
yep .. also makes the logic reusable ...

**Comment by talyssonoc** [comment]
I'm gonna try to tackle that soon and send a PR, thanks, @grosser!

**Comment by alberthu16** [comment]
@grosser is this issue ok to close?

**Comment by grosser** [comment]
thx for looking through the issues :)

**Comment by alberthu16** [comment]
np :)
