### ISSUE TITLE
uninitialized constant Net::HTTP

### ISSUE THREAD

**Issue by simonharrer** [ambethia/recaptcha#169]
Since 3316b8eb3a9043d2369c4f85f73119f1423c1c15 I get the problem that when I use verify_recaptcha I get a `uninitialized constant Net::HTTP` error. How do you solve this problem?

**Comment by grosser** [comment]
looks like you are not using bundler then ... craaaaazyyyyyyy :D 

v1.1.2 should fix things :)

**Comment by simonharrer** [comment]
Hm, I do use bundler. Very strange... for a quick fix I added the require line in the `config/initializers/recaptcha.rb` which solves my issue. But maybe other users are also affected?

**Comment by grosser** [comment]
too late, fixed version is out ...

`ruby -r bundler -e 'Net::HTTP'` works for me ... maybe there are some
old/new bundler versions where that is not true ...

**Comment by alejorivera** [comment]
Just had this same issue. I too was using bundler. Updating to 1.2.0 fixed the issue.
