### ISSUE TITLE
README.md needs updating.

### ISSUE THREAD

**Issue by radicaled** [ambethia/recaptcha#170]
Looks like several options for `recaptcha_tags` don't exist anymore, or have been renamed -- EG, "ajax" option doesn't exist.

**Comment by grosser** [comment]
Want to open a PR ?

On Thu, Mar 31, 2016 at 10:34 PM, Arron Washington <notifications@github.com

**Comment by radicaled** [comment]
I may in sometime this week or next -- ultra busy and haven't gotten back to the ReCaptcha stuff yet.

**Comment by hovissimo** [comment]
Had to go looking through the source for :callback today.
