### ISSUE TITLE
Make Rails Flash Optional

### ISSUE THREAD

**Issue by tomprats** [ambethia/recaptcha#171]
First I'd like to say I'm really grateful for this gem!

But one of the unexpected things when I was using it is that it seems to add the recaptcha message to the flash if it fails. Since I'm using the model implementation, it doesn't make a lot of sense for the error to show up on the user's page twice.

I was wondering if we could add an optional argument as to whether or not it would add anything to the flash object. I'd definitely be willing to submit a pull request if this is something you're interested in.

Thanks!

**Comment by grosser** [comment]
Ideally it should be smart enough to detect wether the model implementation
is used and then not add the duplicate flash ... but option is fine too if
that is tricky ...

**Comment by tomprats** [comment]
That's what I expected it to be like but that might be a breaking change. I could probably go either way though

**Comment by grosser** [comment]
I'd prefer if we try the 'correct' change first :)
If that is somehow a breaking change we can add a changelog entry or
support weird legacy usecases with an option.

**Comment by grosser** [comment]
1.3.0
