### ISSUE TITLE
Secure Token is being deprecated on May 18th

### ISSUE THREAD

**Issue by astuyve** [ambethia/recaptcha#179]
![image](https://cloud.githubusercontent.com/assets/1598537/15049265/26805196-12b3-11e6-9baf-4913ddab651f.png)
We just received this email from reCAPTCHA support, they are deprecating the Secure Token feature as of May 18th.

By default, the `client_helper` includes the secure token unless the option is passed. (https://github.com/ambethia/recaptcha/blob/master/lib/recaptcha/client_helper.rb#L17)

It's unclear at this time what will happen when support for the Secure Token is disabled, but we should work towards removing it.

**Comment by grosser** [comment]
you need to either use domain verification or whitelist all the domains you use
after May 18th we can simply merge a PR that removes secure_token since it will not have any effect ... not sure if the library can do anything to make migration easier ...

**Comment by enorziana** [comment]
I received the same the same email from reCAPTCHA support. I probably can't wait until May 18 for the PR, so I think i just pass in 'stoken: false' and it should still work.

**Comment by grosser** [comment]
yep!

**Comment by astuyve** [comment]
@enorziana you could also uncheck the following box in the recaptcha config dashboard, as long as you validate hostnames on the back end:
![image](https://cloud.githubusercontent.com/assets/1598537/15194470/a4218528-1788-11e6-9719-244e0aa612e7.png)
