### ISSUE TITLE
Why restrict to Ruby 2+?

### ISSUE THREAD

**Issue by brendon** [ambethia/recaptcha#180]
Hi there. I'm totally aware that Ruby 1.9.3 is no longer supported but we're stuck with it for now.

Was there any reason for enforcing Ruby 2+ in terms of code compatibility or was it done for less pragmatic reasons? If there's no code based reason to restrict the Ruby version, then I'd like to table removing that restriction in order to help those of us who are unable to upgrade for now but would still like to use the latest features of this gem. Importantly, with the deprecation of `stoken` and the requirement to verify the host, we NEED to upgrade this gem, and on an urgent timeline.

Perhaps we could integrate `travis-ci` or something like that to run tests across Rubies' and Rails'?

**Comment by brendon** [comment]
Ah I see, you've started supplying parameter names in methods. I guess I'll have to fork this and butcher it for my needs until I can upgrade.

**Comment by brendon** [comment]
Since it's only one method:

` def api_server_url(ssl: nil)`

Would you consider converting it to:

` def api_server_url(ssl = nil)`

just given the current need by everyone to remove the stoken facility?

**Comment by grosser** [comment]
Can't you Pass stoken false with an older Version of recaptcha ?

**Comment by brendon** [comment]
Unfortunately I need to validate the hostname too (and that was introduced after the Ruby 2+ requirement). I was the person who originally introduced the stoken to this gem for that very reason :)

**Comment by brendon** [comment]
In case anyone else comes across this. Here's my branch that removes the restriction:

https://github.com/brendon/recaptcha/tree/remove-ruby-restriction

**Comment by grosser** [comment]
Thx for the link :)

**Comment by Stasik0** [comment]
No merge to master? @brendon is there a way to get trunk patched?

**Comment by grosser** [comment]
maintained on a different branch gem version is 4.6.6.ruby187

**Comment by Stasik0** [comment]
Perfect, unfortunately I am also stuck with an older rails version etc (app from 2010). Ended up using 0.5.0 (seems to work with v2 google api). What are the differences to newer versions?

**Comment by grosser** [comment]
Not sure ... Check chsngelog or merged prs

**Comment by brendon** [comment]
This isn't an issue for me anymore as we're on a newer ruby version.
