### ISSUE TITLE
Global hostname config option (feature request)

### ISSUE THREAD

**Issue by nate00** [ambethia/recaptcha#183]
I would like to have a global `hostname` config option, just like the option to `verify_recaptcha`.

Currently, I have to provide the `:hostname` option on every call to `verify_recaptcha`. If another developer adds another call to `verify_recaptcha` and forgets to provide the `:hostname` option, then they've introduced a security hole (because I unticked the Domain Name Validation box, [as documented here](https://developers.google.com/recaptcha/docs/domain_validation)).

I'd be happy to submit a PR if this is a feature you're interested in.

**Comment by grosser** [comment]
sounds like a useful feature to me, submit away :)
