### ISSUE TITLE
Count verification successes/failures

### ISSUE THREAD

**Issue by nate00** [ambethia/recaptcha#186]
I'd like to be able to be able to count the number of successful and the number of failed calls to `verify_recaptcha`. That would help me notice if I introduced a bug, or if I were still using the old `stoken`, or if a bot is hammering my captcha page.

I'd personally like to count successes/failures with statsd, but it would be nice to support any backend.

Is there already a good way to do this? Otherwise, would you be interested in adding a middleware chain or "around" hooks to `verify_recaptcha`? I can submit a PR in the next few days if you're interested.

**Comment by grosser** [comment]
you can do

def verify_recaptcha(*args)
  result = super
  statsd.report(result)
  result
end

**Comment by nate00** [comment]
That sounds good to me.
