### ISSUE TITLE
recaptcha buttons don't function on IE9 - IE11

### ISSUE THREAD

**Issue by portwood** [ambethia/recaptcha#190]
While testing with IE9-IE11, the recaptcha presents, and I select the images. This works fine. The Verify button as well as the buttons immediately to the left do not respond. IE9-IE11 users cannot continue past the captcha.

**Comment by grosser** [comment]
please submit a PR with a fix if you figure out why that happens, so far never saw this ... can you check if it also fails in the demo ?

**Comment by portwood** [comment]
The issue was caused by the Recaptcha being displayed from a bootstrap modal. I modified my application and I'm closing this issue

**Comment by Totoka** [comment]
I'm getting the same problem here, but also without using modals.
Does this may have something to do by using a div instead of buttons?
