### ISSUE TITLE
recaptcha suppresses other validation errors on form

### ISSUE THREAD

**Issue by marksack** [ambethia/recaptcha#194]
If I use the verify_recaptcha method in the controller as indicated in the readme, i.e.
`if verify_recaptcha(model: @user) && @user.save`
and submit the form with both the recaptcha unchecked and some other error on the form (e.g. a mandatory field left blank), then the errors hash only has the recaptcha error. In order to have all of the errors on the form included, I need to do the following in the controller:
`if @user.validate && verify_recaptcha(model: @user)
  @user.save
  ...
else
  ...`
If this is the intended behaviour, perhaps a note should be added to the documentation.

**Comment by grosser** [comment]
Users will have to re-solve the captcha either way, right ?
... so the advantage is that we show validation errors on invalid captcha
... which should not happen that often ... so I don't think this is a big
win/issue ...

The proposed code would runs validations twice ... so maybe do
`save(validate: false)` if validations are expensive ... and best to chain
it with && in case it still fails.

if @user.validate && verify_recaptcha(model: @user) && @user.save

**Comment by marksack** [comment]
I agree it is not a big issue. I ran into it as I was implementing a form and it has not been reported by any end users. Perhaps it is only a problem for novice users and developers (like me).
But I still think it would be ideal to show all of the errors on the form. The recaptcha error is a relatively simple one and would probably only occur if the element is off screen (need to scroll to see it). Other fields could have more complex validations and I don't see how hiding error messages for such fields could be an advantage.

**Comment by grosser** [comment]
Yep, showing all errors would be best and in most cases potentially running validations twice should not be an issue. Except for when having expensive validations or not wanting bots to be able to spam validations.

I think the default setup is fine / safe ... having this issue will make it easy for others to find how to deal with it ... ideally recaptcha would be another validation on the model ... then we would not have duplicate validation runs ... but that changes the whole setup ...

... overall I think the default is fine and having this searchable issue here is a form of docs/makes it googleable ... so just leave it like that ? :)

**Comment by marksack** [comment]
Yes, this is a good resolution. Thank you.
