### ISSUE TITLE
Integrating recaptcha

### ISSUE THREAD

**Issue by narutoniue** [ambethia/recaptcha#195]
I installed the gem, and followed the instructions.  However, the form is still submitted whether the user does the recaptcha or not.

I'm not sure what I am doing wrong.

controller:

    def create
        @comment = Comment.create(comment_params)
        if verify_recaptcha(model: @comment)
          @comment.save
          redirect_to :back
        else
          redirect_to :back
        end
      end

form:

    <div class="modal fade" id="comment-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-whatever="Type your comment here...">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span class="larger" aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">New Comment</h4>
          </div>
          <div class="modal-body" id="comment-form-div" data-refresh="<%= refresh_url %>">
            <%= form_for Comment.create, remote: true, :html => { id: "comment-form" } do |f| %>
              <div class="row">
                <div class="col-md-10 col-md-offset-1">
                 <div class="form-group">
                    <%= f.label 'Comment' %>
                    <%= f.text_area :body, class: "form-control", id: "bodyText", placeholder:'Type your comments here...' %>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-10 col-md-offset-1">
                  <div class="form-group">
                    <%= f.label 'Email Address' %>
                    <%= f.text_field :email, class: "form-control", id: "email", placeholder:'Enter your email address' %>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6 col-md-offset-1">
                  <%= recaptcha_tags %>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6 col-md-offset-1">
                  <%= f.button "Submit", class: "btn btn-primary btn-lg top-buffer-10", id: "modal-submit", onclick: "commentRefresh()" %>
                </div>
              </div>
            <% end %>
          </div>
          </div>
        </div>
      </div>

js:
    //comment refresh
    function commentRefresh() {
        var refresh = $('#comment-form-div').data('refresh');
        var currentPage = $('#comments').data('page');
        $('#comment-modal').modal('hide');
        setTimeout(function() {
            $.ajax({
                url: refresh,
                data: {
                    page: currentPage
                }
            });
            document.getElementById('bodyText').value='';
            document.getElementById('email').value='';
        }, 500);
    }
    //end comment refresh

**Comment by grosser** [comment]
needs to be `@comment = Comment.new(comment_params)`
