### ISSUE TITLE
Recaptcha v2 doesn't work

### ISSUE THREAD

**Issue by Vizakenjack** [ambethia/recaptcha#199]
I know that 'api.version = 'v2' has gone, but I don't know how to use v2 version of recaptcha. By default, it displays old version and asks user to type a text instead of a checkbox "i'm not a robot".

How can I fix it?

**Comment by grosser** [comment]
demo works just fine ... check that you are using latest version ... 
it now always uses the v2 apis ... so there is nothing you can misconfigure ... unless you overwrote server api urls somehow ...

**Comment by Vizakenjack** [comment]
Oh, looks like i didn't type "bundle update" and there was an old version of recaptcha. Thanks.
