### ISSUE TITLE
Not working from China

### ISSUE THREAD

**Issue by abarriga** [ambethia/recaptcha#200]
China firewal block all google calls, so the recaptcha is not showed and Chinese people are not be able to sign up in our site.

May be loading the js in server instead of client will fix this issue?

**Comment by grosser** [comment]
always needs a call to google to verify ... tell china to stop messing things up :D 
... you need a different captcha provider ... could be neat to have a library that allows easy switching of providers ...

**Comment by grosser** [comment]
... might be able to send it through a proxy and avoid this madness ... https://groups.google.com/forum/#!topic/recaptcha/tCl1AWiMTtk

**Comment by abarriga** [comment]
Proxy stuff works fine, not sure how long... Closeing the issue

**Comment by imWildCat** [comment]
When the frontend API is set to `https://www.recaptcha.net/recaptcha/api.js`, the backend API should be set to `https://www.recaptcha.net/recaptcha/api/siteverify` in order to support Chinese network.

Reference: https://github.com/google/recaptcha/issues/87
Could I create a PR for this?

**Comment by grosser** [comment]
give it a try .... something like "use_dot_net" :)
... maybe that's a better default anyway
