### ISSUE TITLE
Git request from non SSL link

### ISSUE THREAD

**Issue by tbhardwick** [ambethia/recaptcha#206]
Gemlock file generates a git request to a non SSL link:

GIT
  remote: git://github.com/ambethia/recaptcha.git
  revision: 70448ed789e63b4b28f12280d136e79f56e0ff8b
  specs:
    recaptcha (4.0.0)
      json

**Comment by grosser** [comment]
That is your projects Gemfile.lock, so it has nothing to do with this repo.
70448ed is the same code as v4.0.0 ... so just use the gem.
