### ISSUE TITLE
Pagination and Recaptcha

### ISSUE THREAD

**Issue by mahendhar9** [ambethia/recaptcha#209]
Hello. Thanks for the great gem.
I am using recaptcha for a search form. Upon submit, >1000 records matching the search terms are shown on the search results page. I am using 'Kaminari' gem for the search results page pagination. 

However, if I click on one of the inner pages (Page 2, Page 3, etc), it redirects me to the root page.
This my code.

`def search`
`@search = params[:search]`
` if verify_recaptcha && !@search.blank?`
`@records = Book.search(@search).page(params[:page]).per(100)`
`else`
`redirect_to root_path, notice: "Please fill the captcha."`
`end`

How can I fix this?
Thanks.

**Comment by grosser** [comment]
store that the captcha was solved in the initial request

```
if (session[:captcha_solved] ||= verify_recaptcha) && @seach.present?
  ...
end
````
