### ISSUE TITLE
Invisible reCAPTCHA support

### ISSUE THREAD

**Issue by juampi** [ambethia/recaptcha#210]
Is the new invisible reCAPTCHA supported? #207 is the only place I saw it mentioned. However, I don't see how that pull request implements the feature.

If it is indeed supported, it would be nice to have a section in the docs on how to get it working.

**Comment by grosser** [comment]
I'd guess by setting badge ... @ryush00 can you give us some instructions ?

**Comment by juampi** [comment]
When you use the invisible reCAPTCHA, you are not given a button you need to press, but you are shown a little "badge" which tells you that the current page is still reCAPTCHA protected. According to the [docs](https://developers.google.com/recaptcha/docs/invisible#render_param), the `data-badge` attribute is used to reposition that badge. It doesn't seem to magically activate the feature.

There is an attribute which does have something to do with this, which is `size`. When set to `'invisible'`, the button is nowhere to be seen and you are instead shown the badge. However, that's not enough to activate the feature, because the other key attributes will still be in a `<div>` and not in a `<button>`. It may still be possible to use the feature at this point, but further configuration seems to be needed.

It would be nice to have a `recaptcha_button` helper which implements [the easiest method for using the invisible reCAPTCHA](https://developers.google.com/recaptcha/docs/invisible#auto_render).

**Comment by grosser** [comment]
Can you make a PR for that ? :)

**Comment by juampi** [comment]
Yeah, I'm on it.

**Comment by ryush00** [comment]
Thank you for great answer! I was so busy to answer. ;) 

👍
