### ISSUE TITLE
Client connecting through ruby application to recaptcha services

### ISSUE THREAD

**Issue by wyhasany** [ambethia/recaptcha#214]
My web application uses your gem. It is located inside local network and only this host in LAN has access to the Internet. I would like to have a configuration which rewrite scripts to use reverse proxy instead of google web pages. Is it hard to implement that e of functionality?

**Comment by grosser** [comment]
Try proxy https://github.com/ambethia/recaptcha#recaptchaconfigure

... alternatively changing verify_url / api_server_url might work

**Comment by wyhasany** [comment]
This property works only on the server side not on the client.

**Comment by wyhasany** [comment]
I need to edit: 'server_url' => 'https://www.google.com/recaptcha/api.js', from recaptcha.rb

**Comment by grosser** [comment]
make a PR to change it to be configureable (for example like `skip_verify_env`) ... we don't need the CONFIG object anymore

**Comment by sushengloong** [comment]
I created PR #221 to address this issue. For your consideration :smile:

**Comment by grosser** [comment]
PR looks good, should be able to merge that shortly ... closing this
