### ISSUE TITLE
Erro verify_recaptcha

### ISSUE THREAD

**Issue by igortice** [ambethia/recaptcha#215]
```
Recaptcha::RecaptchaError: 784: unexpected token at '<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://ipv4.google.com/sorry/index?continue=https://www.google.com/recaptcha/api/siteverify%3Fsecret%3D6Ldb_SkTAAAAAHbs_I1YQXAGjZP4cm7OY9qe5Yds%26remoteip%3D127.0.0.1%26response%3D03AI-r6f6T4azSHymFjJCc-lj0aKsisGMi2k_JWn7nS3lAgtCkSGEHG2D2-HSOHhjvgRSosaS3jBswvZelWCM---sfpJ5PFOGqBLm06zZyicRZTW1kS4s7Q3C5EIeJIkUOgcyGRKAa60mPyAGFjZrlBYHJ6U3aQiiLtXfvVTyaHzdTrfgUwQP2w2BibAxegUVsSb9N4J0UlqszZaxg4Dv7aLNvkEWI35Mv60KpE4ANITcl8xjvp_u8Bp5lHKTNJ-Nr0NSdrf0UopAhf3yLNnFYdJ6-8py36VIGa1PJTz3Ywgu1-aXj0wDmMDyIpzk27JDTqn2JzWllBx8rLGX4zUbfiJfxrQke24uEW5ydbheEO5VLDczsrq2pZkA&amp;q=EgRA1UACGO26qsYFIhkA8aeDS4Ea9qM2N7CIcfgAYpf2O9T7tvihMgFj">here</A>.
</BODY></HTML>

```

**Comment by grosser** [comment]
does this happen every time ? 
can you reproduce in the demo here ?
any chance you changed the url to something strange and that's why it blows up ?

**Comment by TeamIguana** [comment]
Same problem here.
The gem calls the usual route: "https://www.google.com/recaptcha/api.js?hl=it"
and it temporary redirects to "https://ipv4.google.com/sorry/index" etc.

If you try following the link, there is a warning from google stating that they noticed unusual traffic from the current IP, so they ask to solve a captcha manually to "unlock" the service.

We access it most of the times using Capybara (from automatic tests), so maybe they consider the capybara user agent to be bad and they block the requests from the IP.
We are trying to figure out how to solve it.

**Comment by grosser** [comment]
disable recaptcha during tests ?

**Comment by igortice** [comment]
I do not understand what's happening, but now it's working again

**Comment by grosser** [comment]
glad you fixed it ;)

**Comment by grosser** [comment]
I'll reopen if you have any idea how to fix it ... idk if following the redirect would help ...

**Comment by hrs113355** [comment]
Same problem 12 hours ago, but it seems working again now.
