### ISSUE TITLE
Does this gem support the Invisible reCAPTCHA?

### ISSUE THREAD

**Issue by chayawit** [ambethia/recaptcha#216]
Does this gem support the Invisible reCAPTCHA?

If so, adding the information in the README.md would be nice.

**Comment by grosser** [comment]
yes since https://github.com/ambethia/recaptcha/pull/211, please add docs if you can :)

**Comment by chayawit** [comment]
I would love to do so but I am too inexperienced to even use it in my project. Let alone adding docs.

I am changing back to the normal reCAPTCHA until the guide is available.
