### ISSUE TITLE
verify_recaptcha fails despite valid recaptcha

### ISSUE THREAD

**Issue by githorse** [ambethia/recaptcha#219]
Recaptcha has been working fine for many months, and now suddenly `verify_recaptcha` is failing on every request. The recaptcha in the view seems to be functioning normally (and indicates with a check mark that it's good to go). Here is a sample failing `g-recaptcha-response` param:

`Parameters: { "g-recaptcha-response"=>"03AOP2lf6Sme5I_8G1aOmzZb6Oqn-zZCX8oiEpoK4p9Wjxn7kCfknDw9qtwZLb9Zi9mgD_VoFPIE6sS69_8KIeFiPXy9nfsvz7zlAsbiXtYypnbSSyyUZZTds6_141-bQiYxxnY9IZXJjxizpPHh8FL8tWY07o3oAJbWpmZ5NIuijrmzaTplwKizGTKgQ9aWxNan9DkC41dxvrffz8k4noy_UdVzLvTpeEvSQvn9q6PHEovKPqhZH_M9NUYbSsN3Hqyq1tilnkng_HUhep7YqF10MqJoPK9VuKl6feQljaC0_bVh8fDlBJd4HV0RGp_2PDGZYO6ItRo2gkJgETtk6q-3fQQX_U7Vs9MRXBbUbgSTdI7ny7lzQ4HOFZVRljnUGYtEdl-4ZmQWSeAeYBJ9Cy3nSCyNrrYTDtbO7bgMS09lQ6MCZrs842X11uep2iM1Z4VXtTUuaTscba" }`

I can't find any code I've changed that might have impacted this. Did my keys expire or something? Any idea what might cause this?

**Comment by grosser** [comment]
no idea, please update when you find out ... these bugs are the worst :D

**Comment by gravindra** [comment]
@githorse any update on given issue, do you find solution for this?

**Comment by jonathanrbowman** [comment]
Oddly, when I log `verify_recaptcha` it is always `false`, with class of `FalseClass`.

However, if I define a variable `validated`, and then on ` if verify_recaptcha == true` set `validated` to `true`, and then pivot on THAT variable instead then it actually works. The `validated` variable gets changed properly, even though for some reason `verify_recaptcha` always logs as `false`.

So, this works:

```
    if request.post?
      validated = false

      if verify_recaptcha == true
        validated = true
      end

      if validated == true
        NotificationMailer.media_contact(params[:contact], params[:first_name], params[:last_name], params[:email], params[:message]).deliver

        flash[:success] = "Your message has been successfully delivered."
        redirect_to media_contacts_path
      else
        flash[:error] = "Please include all required form fields, including captcha."
        render action: :media_contacts
      end
    end
```

What in the world is going on?

**Comment by poerror** [comment]
Hi guys, I had same problem when `verify_recaptcha` method was called more than once.
I've fixed this on the front end side by `grecaptcha.reset();` javascript function. This way token for captcha is always renewed after verification.

**Comment by GuillaumeLegendre** [comment]
Hello,

I used the option nonce to reset the js each time on the html tag:
invisible_recaptcha_tags text: 'Confirmer', nonce: SecureRandom.base64(32)

It works great for me.

**Comment by 209cameronism** [comment]
Same exact issue.. don't know how to fix. Here is my controller. 

`class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if verify_recaptcha(model: @contact) && @contact.deliver
      flash.now[:notice] = nil
      redirect_to thankyou_path
    else
      flash.now[:error] = 'Cannot send message. Please try again.'
      render :new
    end
  end
end`

**Comment by grosser** [comment]
hmm maybe add a PR to blow up when validated is called twice ?

**Comment by 209cameronism** [comment]
Hello,
Thank you for your message.I should have been more specific. I was having
problem when using them gem in development mode but I think I read
somewhere this will not work on localhost. Once pushing the update live
onto the server, it work no problem! Thanks so much.
