### ISSUE TITLE
Use Rails button_tag helper for invisible captcha

### ISSUE THREAD

**Issue by ngan** [ambethia/recaptcha#222]
Just wondering if there's a reason to not use button_tag helper for invisible recaptcha? I'm asking because I need to set more attributes on the generated button tag (e.g. disabled and other data-X attributes). With the way it's setup now, you can only specify class it seems.

**Comment by grosser** [comment]
can you make a PR to just dump all the options except text into the button ?

**Comment by ngan** [comment]
Sure thing, I'll give it a go.
