### ISSUE TITLE
How to change the size to compact??

### ISSUE THREAD

**Issue by LBizarre** [ambethia/recaptcha#230]
On mobile the recaptcha goes out of the form I need to make it smaller and find absolutely no solution. Please help, i've tried:
`<%= recaptcha_tags :display => {:size => 'compact', :theme => 'dark'} %>

<%= recaptcha_tags :display => {size: 'compact', theme: 'dark'} %>

<%= recaptcha_tags :size => 'compact'} %>

<%= recaptcha_tags size: 'compact'} %>`

**Comment by grosser** [comment]
check the generated tag, if you pass `size: 'compact'` it should create a `data-size="compact"` attribute
https://github.com/ambethia/recaptcha/blob/master/lib/recaptcha/client_helper.rb#L70-L71

if that does not work, update to latest ... maybe `bundle open recaptcha` ... if size should not be data-size but regular size then this might be a bug and needs a proper fix ... still open the gem, turn it remove `:size` from the list and see if that fixes it

**Comment by LBizarre** [comment]
Thank you, I will try that right away.
Otherwise I'll do CSS solution with style="transform:scale(0.77)"... but size: 'compact should definitely be cleaner.

**Comment by LBizarre** [comment]
Worked! Thanks a lot!
