### ISSUE TITLE
automated tests

### ISSUE THREAD

**Issue by tansaku** [ambethia/recaptcha#232]
is there some standard approach to testing recaptcha with capybara and cucumber, or does that just not make sense, except to test the sad path of failing the robot check ...

**Comment by grosser** [comment]
Don't think you can fully test the happy path ... Just make the controller
always accept the submitted value ...

**Comment by tansaku** [comment]
thanks @grosser - makes sense 

Would be great to see an example sad path in Capybara, but I can probably cook one up :-)
