### ISSUE TITLE
Programmatic invocation of challenge

### ISSUE THREAD

**Issue by MaxBreakfast** [ambethia/recaptcha#239]
Is there a method for programmatically invoking the challenge? This functionality exists in the official documentation:

https://developers.google.com/recaptcha/docs/invisible

**Comment by grosser** [comment]
doubt it exists ... PR welcome

**Comment by thiagok** [comment]
I'm with same problem.

My form have two steps, when user hit enter in first step, the form cannot be sent. I need to perform a validation to send user to next step or send form validating the captcha.

In the documentation, Google says to use a div with params and another button form:
https://developers.google.com/recaptcha/docs/invisible#explicit_render

Any solution?

**Comment by jalkoby** [comment]
checkout #285
