### ISSUE TITLE
localhost:3000 to create recaptcha site key

### ISSUE THREAD

**Issue by rahul2240** [ambethia/recaptcha#241]
While using this gem on localhost:3000, i was unable to use localhost:3000 has a domain in google recaptcha so i think in readme, this should be mention that localhost will work as a domain but not localhost:3000 while trying to create recaptcha site key

**Comment by grosser** [comment]
can you make a PR to add the explanation to the readme ?

**Comment by rahul2240** [comment]
Yes, will do it 😄
