### ISSUE TITLE
Invisible reCAPTCHA - popup with images automatically closes itself

### ISSUE THREAD

**Issue by maurosbu** [ambethia/recaptcha#244]
Hi folks,
I have an issue with invisible reCAPTCHA.

When google is not able to determine whether you are a both or a human then it shows the popup with images.
The problem is that after 2-3 seconds the popup automatically closes itself, the form gets submitted and then an error for invalid captcha is returned.

Any idea on this?

It is working if I don't use the gem and I follow the following instructions: https://developers.google.com/recaptcha/docs/invisible#auto_render 

Many thanks in advance,
Mauro

**Comment by grosser** [comment]
no idea ... maybe `bundle open recaptcha` and mess with the internals ... or compare the html the gem generates with he vanilla html and try to spot a difference

**Comment by maurosbu** [comment]
@grosser sorry, my fault, it works!
