### ISSUE TITLE
Should g-recaptcha-response be validated before sending to Google?

### ISSUE THREAD

**Issue by jablan** [ambethia/recaptcha#246]
We had an issue when a hacker issued multiple requests with forged value in captcha response. The response was apparently too long and Google responds with 400. It is not a security issue, but I'm wondering whether Google somehow penalizes such attempts, and therefore, whether recaptcha should validate the response before sending it to Google?
Thoughts welcome.

**Comment by grosser** [comment]
Seems like a strange edge-case ... most likely the hackers learned from the mistake and won't do that again ... there is no advantage to them I'd think.
Never heard of captchas getting rate-limited, so let's wait until it is a problem ...
Feel free to implement some validation in your controller if you want to avoid the overhead of sending known bad things to google ... but I'd think few others have the same issue.
Please share your solution here if you end up building something like that.
