### ISSUE TITLE
Disabled attribute on invisible recaptcha not showing up on submit button

### ISSUE THREAD

**Issue by timurista** [ambethia/recaptcha#248]
`= invisible_recaptcha_tags text: 'join', id: 'signup', badge: 'bottomleft', disabled: 'disabled', foo: 'bar'`

spits out this html:
```html
<button type="submit" class="g-recaptcha " data-badge="bottomleft" data-callback="invisibleRecaptchaSubmit" data-sitekey="6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI" id="signup" foo="bar">join</button>
```
it includes all the tags correctly except disabled. I want to disable the form until the user has filled out some information. Any ideas why disabled isnt working here?

**Comment by grosser** [comment]
https://github.com/ambethia/recaptcha/blob/master/lib/recaptcha/client_helper.rb#L54 looks like it's adding it to the tag ... `bundle show recaptcha` and add some debugging ... maybe it gets removed by js/browser ... make sure to "View Page Source"

**Comment by timurista** [comment]
yep view page source shows it ("disabled"=disabled), but it is not disabled nor inheriting my disabled styling. It's like disabled is getting turned off from recaptcha js

**Comment by timurista** [comment]
it's only the invisible recaptcha, the recaptcha_tags work fine.

**Comment by grosser** [comment]
then make it disabled again via js ? :D

**Comment by timurista** [comment]
what we ended up doing was disabling via js and doing css styling to handle the onload case. So it at least looks disabled. It is still technically clickable but there's backend logic to prevent anything malicious. Thank you, closing this
