### ISSUE TITLE
we need a test that runs without rails

### ISSUE THREAD

**Issue by grosser** [ambethia/recaptcha#257]
just saw a PR that used a rails-only method and nothing failed

**Comment by piotrze** [comment]
@grosser I this you can close this after: https://github.com/ambethia/recaptcha/pull/336

**Comment by grosser** [comment]
no test failed when that method was added ... so we still need that test :)

**Comment by nruth** [comment]
Maybe this can be closed now?

When I put those methods back in the tests do fail. 

![image](https://user-images.githubusercontent.com/26158/95409730-30f38f00-091a-11eb-8859-06cf5fbc212e.png)

There's also no Rails anywhere in the Gemfile, so not sure how you'd run a test with rails at the moment.

**Comment by grosser** [comment]
thx for the update, yeah seems done!
