### ISSUE TITLE
Backport to Ruby 1.8.7, Rails 2.3?

### ISSUE THREAD

**Issue by kookster** [ambethia/recaptcha#261]
I have an ancient app that used an old version, needed to upgrade it, so I backported this gem to work on Rails 2.3 and Ruby 1.8.7 (enterprise edition)

https://github.com/PRX/recaptcha/tree/backport_ruby187_rails23

I suspect you don't want these changes in master, but thought I would add an issue here for any fellow travelers to find, and offer to provide a PR for this support in a branch if anyone was interested.

**Comment by grosser** [comment]
want make a PR against rails23 branch so it lives in this repo too ?

**Comment by kookster** [comment]
great, done! https://github.com/ambethia/recaptcha/pull/262

**Comment by kookster** [comment]
and now this is a branch for anyone that wants it:

https://github.com/ambethia/recaptcha/tree/rails23
