### ISSUE TITLE
Updating Rails 2.3.17, Ruby 1.8.7

### ISSUE THREAD

**Issue by scottrCT** [ambethia/recaptcha#272]
Doing a rake gems:install on this in the environment.rb:
`config.gem 'recaptcha', :require => 'recaptcha/rails', :source=>'https://github.com/ambethia/recaptcha/tree/rails23'`
results in the following error:
`gem install recaptcha --version ">= 0" --source https://github.com/ambethia/recaptcha/tree/rails23
  ERROR:  Could not find a valid gem 'recaptcha' (>= 0) in any repository
  ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
  bad response Not Found 404 (https://github.com/ambethia/recaptcha/tree/rails23/latest_specs.4.8.gz)`

Running `gem install 'recaptcha' --source='https://github.com/ambethia/recaptcha/tree/rails23'` gives a similar error.

Ruby = 1.8.7-p376
Rails = 2.3.17

Any ideas?

**Comment by grosser** [comment]
use https://rubygems.org/gems/recaptcha/versions/4.6.6.ruby187
