### ISSUE TITLE
Rails (5.2.0) reCaptcha Devise (4.4.3) undefined method users_url

### ISSUE THREAD

**Issue by vohaul** [ambethia/recaptcha#275]
Not sure if it is actually a bug. 
Full description here on [stackoverflow](https://stackoverflow.com/questions/50476836/rails-5-2-0-recaptcha-devise-4-4-3-undefined-method-users-url) 
Looks like it happens only in case of confirmable and only in test environment
I use quite a dirty trick  to bypass it now
```
    def check_captcha
      return true if Rails.env.test?
      unless verify_recaptcha
        self.resource = resource_class.new sign_up_params
        resource.validate # Look for any other validation errors besides Recaptcha
        set_minimum_password_length
        respond_with resource
      end
    end
```

**Comment by grosser** [comment]
no idea ... needs some reproduction repo for proper debugging

**Comment by vohaul** [comment]
@grosser check out https://github.com/127/recaptcha-bug-rails

**Comment by grosser** [comment]
does not boot and after fixing some things fails with db error ... can you document how to see the error and ideally make the app boot when cloned ?

**Comment by vohaul** [comment]
I've updated the following example. It boots with ```rails db:setup && rails s```
rails test:system fails with
```
Error:
UsersTest#test_creating_a_user:
NoMethodError: undefined method `users_url' for #<RegistrationsController:0x00007fe1d7d387e8>
Did you mean?  user_session_url
Did you mean?  user_session_url
    app/controllers/registrations_controller.rb:33:in `check_captcha'
```

**Comment by grosser** [comment]
if you remove recaptcha it also fails ...

controller does not inherit from ApplicationController so it cannot build urls

```
def check_captcha
      #dirty hack
      # return true if Rails.env.test?
      # unless verify_recaptcha
        self.resource = resource_class.new sign_up_params
        resource.validate # Look for any other validation errors besides Recaptcha
      #   set_minimum_password_length
        respond_with resource
      # end
    end
```

**Comment by vohaul** [comment]
Of course it does not. Everything is done according official recommendation at
https://github.com/plataformatec/devise/wiki/How-To:-Use-Recaptcha-with-Devise
So expected to be working with blank apps. 

```
class RegistrationsController < Devise::RegistrationsController
  prepend_before_action :check_captcha, only: [:create] # Change this to be any actions you want to protect.

  private
    def check_captcha
      unless verify_recaptcha
        self.resource = resource_class.new sign_up_params
        resource.validate # Look for any other validation errors besides Recaptcha
        set_minimum_password_length
        respond_with resource
      end 
    end
end
```

And it looks absolutely isotheric by the way

- works ```rails test test/system/registration_test.rb```
- fails the same test with ```rails test:system```

**Comment by vohaul** [comment]
by the way ```verify_recaptcha``` always returns false in test

**Comment by grosser** [comment]
I meant that the error is coming from the setup/device and is not related
to recaptcha in any way.

verify_recaptcha might return true when passing in a
params['g-recaptcha-response'] see
https://github.com/ambethia/recaptcha/blob/master/lib/recaptcha/verify.rb#L15

**Comment by yunixon** [comment]
devise (4.6.1)
recaptcha (4.13.1)

Temporary fixed by adding custom error:

```
def check_captcha
    return if verify_recaptcha

    self.resource = resource_class.new sign_up_params
    resource.validate
    set_minimum_password_length
    **resource.errors.add(:base, 'reCAPTCHA verification failed, please try again')**
    respond_with resource
  end
```
