### ISSUE TITLE
"reCAPTCHA verification failed, please try again" in test environment with invisible reCAPTCHA

### ISSUE THREAD

**Issue by tirdadc** [ambethia/recaptcha#276]
A spec that would test a contact form and used to pass successfully now only passes in isolation and no longer as part of the whole test suite.

Looking at the details, I see:

```
Failures:

  1) Visitor uses contact form it submits a filled form and gets a success message
     Failure/Error: expect(page).to have_content('Your message has been successfully sent.')
       expected to find text "Your message has been successfully sent." in "\nreCAPTCHA verification failed, please try again.×"
     # ./spec/features/visitor_uses_contact_form_spec.rb:23:in `block (2 levels) in <top (required)>'
```

Why is `CAPTCHA verification failed, please try again` even showing there when it should not be enabled in test mode?

I am using the invisible reCAPTCHA and the gem's version is 4.8.0.

**Comment by grosser** [comment]
sounds like it relied on some pollution happening elsewhere ... try running
just a few files and keep the --seed then see when it starts going green

**Comment by grosser** [comment]
hoping this is fixed by the "prefer RAILS_ENV over RACK_ENV" change, plz give v4.11.0 a try

**Comment by tirdadc** [comment]
Just tried it out, that did fix it. Thanks!
