### ISSUE TITLE
Call verify_recaptcha from outside of a controller in rails

### ISSUE THREAD

**Issue by aqeelvn** [ambethia/recaptcha#277]
It looks like I can't call the `verify_recaptcha` method from outside a controller as it directly refers to a `request` object: https://github.com/ambethia/recaptcha/blob/master/lib/recaptcha/verify.rb#L21

For example I would like to call the method from a different service object which does form related validations, but currently it would give me an error like: 
```
undefined local variable or method `request' for ...
```

Is this a limitation of the gem or am I missing something?

**Comment by grosser** [comment]
it's built to be used in controllers ... so either create a fake request object or make a PR to make request optional

**Comment by aqeelvn** [comment]
@grosser Thanks for confirming. I'll go with the second approach to begin with. I'll submit a PR if I have the time to refactor
