### ISSUE TITLE
Invisible recaptcha asks to select images in incognito mode

### ISSUE THREAD

**Issue by imi56** [ambethia/recaptcha#287]
It works like a charm in normal mode, but in incognito mode it makes users choose the images.
```
gem "recaptcha", "~> 4.10.0"
Chrome Version 68.0.3440.75 (Official Build) (64-bit)
```

**Comment by grosser** [comment]
that's not something this gem controls, I bet that's google saying "I don't trust your incognito browser" ... try with a raw recaptcha and I bet it's the same result, feel free to reopen if there is anything to do in the gem
