### ISSUE TITLE
reCAPTCHA v3 support

### ISSUE THREAD

**Issue by barrywoolgar** [ambethia/recaptcha#296]
Hello, I happened to start using this gem yesterday and didn't realise v3 had only just been released. 

Obviously I don't expect the gem to support that straight away, but I'm writing this so that anyone else will know that using v3 credentials and invisible tags does not seem to ever bring up the image picker and appears to let every request through the controller verification as if they were successful. 

Switching to v2 credentials started working as expected with no fuss.

Thanks

**Comment by grosser** [comment]
PR welcome, I have not tried v3 yet

**Comment by barrywoolgar** [comment]
Yup, bit stacked at the moment but will have a go if nobody beats me to it.

Looks like the script/verify paths are the same, just that the response `success` will now always be true for a valid token, and a new `score` value is returned that would be used to decide whether to accept or not (0.0 for definite-bots, 1.0 for definite-human). 

There's more to it (the concept of scores per action, including the script on every page, etc), but just checking the `score` value looks like the minimum level of support needed in the first instance.

**Comment by vaishnavi3** [comment]
has v3 been implemented yet??how to set minimum_score which is part of v3??

**Comment by kissu** [comment]
> has v3 been implemented yet??how to set minimum_score which is part of v3??

Not sure about the implementation but the `minimum_score` is set into the Google console no ?

**Comment by vaishnavi3** [comment]
From official docs "reCAPTCHA v3 returns a score (1.0 is very likely a good interaction, 0.0 is very likely a bot). Based on the score, you can take variable action in the context of your site."...I would like to get the score and do things if score is less..

**Comment by kissu** [comment]
For that, you need to get the returned callback.
> https://developers.google.com/recaptcha/docs/v3

**Comment by TylerRick** [comment]
I'm working on adding v3 support. I'll push up a PR soon...

**Comment by GaganGami** [comment]
I had added this gem and setup V3 for my project. was stuck with Error Invalid key. After lots of struggle come to know V3 is not supported through this gem. So I switched to V2 at the moment. Waiting for New Release.

**Comment by TylerRick** [comment]
Ok, I just opened a PR at #310 with v3 support. Please comment there if you have any questions or suggestions.

**Comment by ulisescarreonalvarez** [comment]
Hi @TylerRick the v3 support will be ready on this days?

I wanna give a try.

**Comment by TylerRick** [comment]
You can try it out by adding this to your Gemfile:
```
gem 'recaptcha', github: 'TylerRick/recaptcha', branch: 'v3'
```
(and refer to the docs here: https://github.com/TylerRick/recaptcha/tree/v3#recaptcha_v3)
