### ISSUE TITLE
Not able to display error messages

### ISSUE THREAD

**Issue by oktalk** [ambethia/recaptcha#305]
Typical form inputs have validation errors that are displayed via the code below. The Recaptcha gem however doesn't seem to follow this pattern. How can I access the error message? It's not `recaptcha_error`, or `reCAPTCHA`, or `recaptcha` so what is it? Any help would be greatly appreciated.
 
 ```
   <%= recaptcha_tags %>
    <% if errors? entry, :recaptcha %>
      <div class="invalid-feedback">
        <%= error_details entry, :recaptcha %>
      </div>
    <% end %>
```

**Comment by grosser** [comment]
- `flash[:alert] = "Fill captcha correctly"`
 -  set `@recaptcha_error = ` and then show that in the form
 - use `:model` and then show errors with rails helpers
