### ISSUE TITLE
parameters changed (since older version) to 'g-recaptcha-response': grecaptcha.getResponse()

### ISSUE THREAD

**Issue by jywarren** [ambethia/recaptcha#315]
I was upgrading from an old version and had to change the request to the below format when initiating an ajax request; just in case this is helpful for others! 

```js
      $.ajax({
        url: '/maps/export/13085?authenticity_token=M0H/vun6JMWHgyxCro6z/pjhPo0SRAvxoqvqHMnJruU=',
        method: 'POST',
        data: {
          'g-recaptcha-response': grecaptcha.getResponse(),
          resolution: exportResolutionSlider.val()
        }
      })
```

https://github.com/publiclab/mapknitter/blob/3d25dc7bdaff774b4ae256ea98d0a71f2d70a11b/app/views/maps/_sidebar_exports.html.erb#L161-L169

**Comment by grosser** [comment]
can you make a PR to add this to the changelog ?

**Comment by jywarren** [comment]
Sure! Happened here: https://github.com/ambethia/recaptcha/pull/114

PR here: https://github.com/ambethia/recaptcha/pull/316
