### ISSUE TITLE
undefined method `recaptcha_v3'

### ISSUE THREAD

**Issue by charlesdeb** [ambethia/recaptcha#319]
I can see this feature has only just been added to the gem, so a few teething problems are to be expected!

My problem is this: I installed the gem,did bundle install and set up my v3 keys on Google, and received the above error. I checked a bunch of stuff (chose specific git branches and commits to use in my gemfile), and when I couldn't download the latest master branch with the new v3 stuff in it, gave up and tried to use v2. But after more fiddling round, I noticed that the v3 stuff _was_working again and so I implemented it. It works well BTW.

But when it came time to deploy onto my staging site (via heroku) the error surfaced again there - and it has no shown up again locally. Checking the contents of the gem, I can see that the files referencing recaptcha_v3 are old. I am not totally au fait with gem spec files and the like, but I suspect you need to bump the version number as 4.14.0 doesn't have v3 support in it, but that is what bundler seems to be giving me most of the time.

**Comment by grosser** [comment]
setup should look like:
```
gem 'recaptcha', git: "https://github.com/ambethia/recaptcha.git"
```

and then `bundle update recaptcha` for good measure
is this a rails app ? if not, where did you include Recaptcha::Adapters::* ?

**Comment by charlesdeb** [comment]
Weird. That was my set up. But I deleted the gem and did a reinstall and it seems to be working fine now. And up on heroku as well. Not sure what I got wrong in this process... but thanks for your help.
