### ISSUE TITLE
In-gem translations?

### ISSUE THREAD

**Issue by JasonBarnabe** [ambethia/recaptcha#326]
I can see from https://github.com/ambethia/recaptcha#i18n-support that `recaptcha.errors.verification_failed` and `recaptcha.errors.recaptcha_unreachable` are the keys to use for localization. I was going to add these to my project which supports 34 languages, but I figured it may be better to share the work with everyone.

Is there interest to add the translations to the gem directly? I can point my translators here once it's set up.

**Comment by grosser** [comment]
having them available here, even if it's just for copy-paste would be an
improvement, so please do it :)
