### ISSUE TITLE
Get a score from verify_recaptcha for V3

### ISSUE THREAD

**Issue by jirihradil** [ambethia/recaptcha#329]
Is it possible to get the result score from any gem's method when using reCAPTCHA v3? Took a look at the source but the current `verify_recaptcha` method only returns true/false. Maybe there is another way how to get the score by using another method without a need to write a custom implementation?

However, thanks for the great gem, really appreciate it!

**Comment by grosser** [comment]
- only way I see to not add a custom implementation is putting another option into `verify_recaptcha` that then somehow returns the score ... but that might turn out ugly
 - does passing `minimum_score: 0.9` help ?
 - why do you need the score ?

**Comment by jirihradil** [comment]
I would like to get the score for logging purposes and also for setting up a right minimum_score. We can use statistics from Google but they are delayed; getting the score immediately would allow us react/tune up the score faster.

**Comment by grosser** [comment]
This might work:
```Ruby
class << Recaptcha
  prepend(Module.new do
    def api_verification(*)
      result = super
      Rails.logger.info "Recaptcha result #{result}"
      result
    end
  end)
end
```

otherwise PR welcome, unless it ends up a giant spaghetti mess :(

**Comment by jirihradil** [comment]
Super, will try. Thanks!
