### ISSUE TITLE
How to change the position of recaptcha_tags

### ISSUE THREAD

**Issue by Danissss** [ambethia/recaptcha#330]
I have tried:

`<%= recaptcha_tags :style => "text-align: center;"%>`

and at style

```
.g-recaptcha {
         display: -webkit-flex; /* Safari */
	-webkit-align-items: center; /* Safari 7.0+ */
	display: flex;
	align-items: center;
}
```

Thanks!

**Comment by grosser** [comment]
can you explain more of what "change position" means, ideally screenshots or even better make a fork and  show the issue in the example app

**Comment by Danissss** [comment]
<img width="1184" alt="Screen Shot 2019-08-15 at 12 04 55 PM" src="https://user-images.githubusercontent.com/21318412/63115754-224b5b00-bf55-11e9-8415-346c0681cb31.png">
I want to center this tag.
Thanks!

**Comment by grosser** [comment]
ugh yeah that's ugly :D
inspect and play with the css until it's nice ... otherwise edit the html in the browser until it's workable and then make a PR to add what's needed (like a surrounding div or so)

**Comment by Danissss** [comment]
`<%= recaptcha_tags :align => "center" %>` should work

**Comment by grosser** [comment]
then all is good / can close ?

**Comment by radinreth** [comment]
sorry for interrupt!

In this case, google also provide an option so you don't have to manually update your CSS.

Below is what I have done :)

`invisible_recaptcha_tags ui: :invisible, "data-badge": "bottomleft"`

For more detail: https://developers.google.com/recaptcha/docs/invisible#config
