### ISSUE TITLE
[Recaptcha v3] verify_recaptcha method returning false

### ISSUE THREAD

**Issue by rodrigopinto** [ambethia/recaptcha#331]
I am running the Recaptcha with the v3 and the `verify_recaptcha` is returning false even when the response is a success.

```sh
2019-08-22T14:10:04+02:00 DEBUG [httplog] Response:
{
  "success": true,
  "challenge_ts": "2019-08-22T12:10:02Z",
  "hostname": "localhost",
  "score": 0.9
}
```
The response makes sense according to the API documentation https://developers.google.com/recaptcha/docs/verify#api-response

But inside the `verify_recaptcha` it runs the `self. verify_via_api_call ` that [tries to verify if the action is valid](https://github.com/ambethia/recaptcha/blob/c9ef2815a3c3d7b8e0abd4b5b85207a34db23cc0/lib/recaptcha.rb#L70), but the response of the "siteverify" request does not include the action on the response body. 

```ruby
verify_recaptcha(action: "user_registration_form", minimum_score: 0.7) # => false
```

**Comment by grosser** [comment]
Hmmm no idea why that would happen, can you reproduce in the demo app ?
Otherwise I'd recommend to `bundle open recaptcha` and add some debugging
`puts` throughout the method to see where that `false`  comes from

**Comment by julianrubisch** [comment]
I'm hitting the same problem, just wanted to add to this that the v3 docs actually state that there is an `action` in the response body: https://developers.google.com/recaptcha/docs/v3#site-verify-response

**Comment by julianrubisch** [comment]
However, nvmd, in my case it must be something different... not seeing any http calls at all... probably need to `bundle open` as well

**Comment by dvdoliveira** [comment]
I'm seeing the same problem reported by @rodrigopinto above. At first, I thought that I was putting the `mininum_score` parameter too high (0.6) and, even after bringing the `minimum_score` to `0.2`, I still get recaptcha validation as `false` when the response from Google is a success.

**Comment by bilouw** [comment]
Hi ! Any ideas for this issues? The methods return false for me too, even if the score is high ...

**Comment by grosser** [comment]
FYI `recaptcha_reply` controller method can be used to dump the actual reply, might make debugging/logging easier ... needs >= 5.5.0

**Comment by ArunRathore247** [comment]
Hi guys, I'm also getting the same issue. Any update or any patch or fix you have done for this issue ?

**Comment by grosser** [comment]
use `recaptcha_reply` to dump the response and debug what went wrong

**Comment by javedhussain** [comment]
Guys, I'm also facing the same issue. 
![Screenshot 2020-04-17 at 8 48 51 PM](https://user-images.githubusercontent.com/4439603/79585297-3b606900-80ed-11ea-818b-423969b1fb35.png)


Any update?

**Comment by grosser** [comment]
use the `recaptcha_reply` method after calling `verify_recaptcha`

**Comment by javedhussain** [comment]
yeah, I did that too. It returns `nil`.

**Comment by grosser** [comment]
... maybe you are running in development mode ?
`gem open recaptcha` and see why it would stop early

**Comment by javedhussain** [comment]
It worked for me! did a silly mistake in the secret and site key.

**Comment by jamesdixon** [comment]
I believe this is still a valid issue.

In my case, I'm using `recaptcha_v3` on two different forms. One of them has an action of `login` and another has an action of `sendEmail`. Login works fine but when sending the email, I'm seeing the response contain the following even through the action passed to `recaptcha_v3` is `sendEmail`:

`{"success"=>true, "challenge_ts"=>"2020-10-05T19:56:43Z", "hostname"=>"localhost.spectora.com", "score"=>0.9, "action"=>"login"}`

If I skip action validation using `verify_recaptcha!(action: false)`, it returns success as expected. It seems like the action name is being cached?
