### ISSUE TITLE
not working on Herku

### ISSUE THREAD

**Issue by frobert** [ambethia/recaptcha#339]
recaptcha works locally and on other production and test servers but not on Heroku...
The box is not showing up and there are no errors in browser console.

Using v2, I'm not a robot captcha.

**Comment by grosser** [comment]
please update if you find anything ... ideally make a small example app so it's easier to reproduce / others can help

**Comment by frobert** [comment]
my bad, recaptcha is disabled on TEST environment by default... Closing issue.

`Recaptcha.configuration.skip_verify_env.delete('test')`

**Comment by grosser** [comment]
thx for reporting with the fix :)
