### ISSUE TITLE
cant vaild captcha response code on mobile

### ISSUE THREAD

**Issue by huuhait** [ambethia/recaptcha#341]
hi i have tested recaptcha in pc it working normal
with same sitekey/config
i have tested in mobile recaptcha ruby cant vaild

but i test verify code via `https://www.google.com/recaptcha/api/siteverify` it say: `success: true`

**Comment by grosser** [comment]
no idea ... try js console to see if that shows anything or `bundle open
recaptcha` to see where it fails
example app with the failure could also help in debugging

**Comment by huuhait** [comment]
![image](https://user-images.githubusercontent.com/40519768/70665013-2d618e00-1c9e-11ea-9ddd-85e17f1782bd.png)
hi idk what editor should be use for open recaptcha
can u suggest for me?

**Comment by grosser** [comment]
EDITOR=subl
EDITOR=mine
... or do bundle show recaptcha and then open files in whatever

**Comment by huuhait** [comment]
error by recaptcha

close issuse!
tks for your support :)

**Comment by grosser** [comment]
might still be able to improve the error message / make debugging easier if
you got any ideas for that :)
