### ISSUE TITLE
Turbolinks and Recaptcha

### ISSUE THREAD

**Issue by paulbaum** [ambethia/recaptcha#342]
we use this gem in 3 scenarios. One of them does not use turbolinks and it works flawless.
The other 2 pages have turbolinks enabled. 
With recaptcha v3 and fallback v2 we experienced different errors.

The first one that came up was:
**"grecaptcha not defined"** as library loading seems to not be in sync when using turbolinks.
There were some solutions for older rails versions but using 6 nothing has worked to fix the error.
We therefore removed the immediate execution of executeRecaptchaForRequest and instead passed this as a callback into the  api.js url in order to have it executed when the library has been loaded.

This fixed the error but then the definition of the async method led to a syntax error **"unexpected token function"**. Since we already used a patch we also deleted this definition since we don't use it right now. This worked for us but is not really the good way and can crash when recaptcha gets updated.

Are there any solution I missed working with rails 6? (ajax: true didn't work for us)

**Comment by grosser** [comment]
idk of any fix for this, please dig deeper and post your findings here /
make a PR :)

**Comment by estani** [comment]
This does seem to work, but in the console I get an error when starting from a different page, navigating to the form, then away again and then coming back to it:
```
recaptcha__de.js:279 Uncaught Error: reCAPTCHA placeholder element must be empty
```
The form does seem to work properly though. The recaptcha badge on the bottom right is not expanding anymore though, thus not displaying the legal infos.

**Comment by paulbaum** [comment]
@estani seems to be another/extended issue. I'll close this for now, you can create a new one for your specific problem :)

**Comment by estani** [comment]
ok!
