### ISSUE TITLE
Getting the v3 humanity score

### ISSUE THREAD

**Issue by esale** [ambethia/recaptcha#343]
Hi,

I'd like to get the humanity score reported by Google. In you doc says

> You need to verify this token with verify_recaptcha in your controller in order to get the score.

but I can't get the score, only a boolean.

Is there any way to get the actual number? There is another gem, new_google_recaptcha that can report the score to the controller.

Regards and thanks in advance.

**Comment by grosser** [comment]
need to call api_verification manually like done here https://github.com/ambethia/recaptcha/blob/43c1a5dd460c6ee2abf4dd6d59775a4f79cd0fd7/lib/recaptcha.rb#L67
PR to optionally return the full response instead of true would also be welcome since that was asked for before

**Comment by esale** [comment]
Hi,

I didn't do a PR, but I think maybe [the code in this gist](https://gist.github.com/esale/c4d08377d5df5ce6b2540358946e16a3) could be added to your project.

Is it helpful?

I used verify_recaptcha as skeleton. In my project, I'm currently using what you suggested as:

`Recaptcha.api_verification({secret: Recaptcha.configuration.secret_key, response: recaptcha_response_token("contact")})`

and it works fine.

Thanks and regards.

**Comment by grosser** [comment]
looks about right PR would be nice :)

**Comment by Intrepidd** [comment]
I have started working on it in #358, would love your opinion on it so we can make it happen !

**Comment by grosser** [comment]
5.5.0
