### ISSUE TITLE
Rails 6.0+ Support

### ISSUE THREAD

**Issue by dwood-somniainc** [ambethia/recaptcha#345]
The gem doesn't install with Rails 6. Will we be getting support soon?

**Comment by grosser** [comment]
PR welcome!

**Comment by archonic** [comment]
I had no problem installing recaptcha 5.3.0 on Rails 6.0.2.1.

**Comment by grosser** [comment]
@dwood-somniainc can you post the error message ?

**Comment by isy** [comment]
[FYI]
Rails v6.1, recaptcha v5.1.0, devise v4.7.1

`verify_recaptcha` always became false in the above environment.

```ruby
valid = verify_recaptcha(model: @user, action: 'registration', minimum_score: 0.5)
# => false
```

When recaptcha was upgraded to v5.5.0, it worked normally
