### ISSUE TITLE
Single quoting env vars causes JS error

### ISSUE THREAD

**Issue by archonic** [ambethia/recaptcha#347]
If you have a .env with this:
```
RECAPTCHA_SITE_KEY='xxx'
RECAPTCHA_SECRET_KEY='yyy'
```

This will generate JS which has a syntax error:
`Uncaught SyntaxError: missing ) after argument list`

It should be pretty simple to accommodate env variables with single quotes.

**Comment by grosser** [comment]
sounds more like your env vars are not parsed correctly ... do `puts ENV["RECAPTCHA_SITE_KEY"].inspect` ... it most likely shows up as `"'RECAPTCHA_SITE_KEY'"`
