### ISSUE TITLE
Invisible reCAPTCHA does not work

### ISSUE THREAD

**Issue by tkimi** [ambethia/recaptcha#355]
when updated to v5.4.0

I think there is a cause in textarea render by "[recaptcha.js](https://www.google.com/recaptcha/api.js)".

class and name attributes are `g-recaptcha-response`, not `g-recaptcha-response-data`.
```
function(z,H){return S('<textarea id="'+(H=z.name,U)(z.id)+'" name="'+U(H)+'" class="g-recaptcha-response"></textarea>')})
```

**Comment by grosser** [comment]
sounds like https://github.com/ambethia/recaptcha/pull/354 broke it ... can you make a PR with a fix ?

@finist can you take a look ?

**Comment by finist** [comment]
For checking recaptcha, using token which is stored in `g-recaptcha-response-data`, @tkimi can you check do you have `g-recaptcha-response-data` field with non empty value?

**Comment by paulodeon** [comment]
5.4.0 broke my visible recaptcha as well. Also there was no changelog with it

**Comment by grosser** [comment]
https://github.com/ambethia/recaptcha/pull/356 looks like it's going in the right direction ... just needs to be tested on v2 and v3 I think ... any help is appreciated :)

**Comment by Zhao-Andy** [comment]
Hi all, made this comment in #356 but also leaving it here in case it's helpful. I did this as a short term solution:

```ruby
verify_recaptcha(secret_key: your_app_secret, response: params["g-recaptcha-response"])
```

**Comment by grosser** [comment]
5.4.1
