### ISSUE TITLE
reCAPTCHA Unexpected token in JSON at position 0

### ISSUE THREAD

**Issue by kookster** [ambethia/recaptcha#373]
Anyone else having this issue with reCaptcha & rails?
https://stackoverflow.com/questions/64737646/recaptcha-unexpected-token-in-json-at-position-0
```
Uncaught (in promise) SyntaxError: Unexpected token x in JSON at position 0
at JSON.parse (<anonymous>)
at recaptcha__en.js:24
at recaptcha__en.js:45
at Array.<anonymous> (recaptcha__en.js:307)
at Array.<anonymous> (recaptcha__en.js:44)
at js.$ (recaptcha__en.js:23)
at Array.<anonymous> (recaptcha__en.js:195)
at zO.g.next (recaptcha__en.js:370)
at P (recaptcha__en.js:41)
```

**Comment by grosser** [comment]
make it dump what the response was, most likely some 500 that came in as
html

**Comment by kookster** [comment]
We figured it out - there was another javascript file included which was causing a conflict (gotta love those minified js files...).
Changed the page to only load a minimum of js, and it all works.
