### ISSUE TITLE
Token needed in verify_recaptcha?

### ISSUE THREAD

**Issue by asadakbar** [ambethia/recaptcha#377]
Hi, does the v3 token need to be passed to verify_recaptcha in a controller? The documentation is confusing so I'm not sure. 

In the first paragraph of this section of the readme [recaptcha_v3](https://github.com/ambethia/recaptcha/blob/master/README.md#recaptcha_v3), it mentions 

> and calls the callback with the resulting response token. You need to verify this token with verify_recaptcha in your controller in order to get the score.

However, none of the examples of `verify_recaptcha` show the `g-recaptcha-response` param being passed to it. The only two options are `action` and `minimum_score`. If these are the only two needed, how does `verify_recaptcha` verify the token we were given? Examples are shown [here](https://github.com/ambethia/recaptcha/blob/master/README.md#verify_recaptcha-use-with-v3), [here](https://github.com/ambethia/recaptcha/blob/master/README.md#multiple-actions-on-the-same-page), [here](https://github.com/ambethia/recaptcha/blob/master/README.md#recaptcha_reply) and several [here](https://github.com/ambethia/recaptcha/blob/745720d935699ae76456268de344176d3adabfcd/demo/rails/app/controllers/v3_captchas_controller.rb#L6).

**Comment by grosser** [comment]
Yeah, I think the v3 key always needs to be passed.
see https://github.com/ambethia/recaptcha#recaptcha-v3-api-and-usage
the docs sure could need some love, so if you figure it out / know what was
misleading, plz update them

**Comment by asadakbar** [comment]
So I got a chance to dig into the code a bit and it turns out that the token does not need to be passed because verify_recaptcha digs into the params and pulls the value out. 

However it first sees if the token was passed to `verify_recaptcha` explicitly with an optional `:response` key https://github.com/ambethia/recaptcha/blob/745720d935699ae76456268de344176d3adabfcd/lib/recaptcha/adapters/controller_methods.rb#L16

If it isn't passed in, then the token is extracted out from the params here https://github.com/ambethia/recaptcha/blob/745720d935699ae76456268de344176d3adabfcd/lib/recaptcha/adapters/controller_methods.rb#L85.

So I think the only thing needing to be updated is the docs. I'll try to submit a pr soon.

**Comment by grosser** [comment]
Awesome, thx!
