### ISSUE TITLE
TypeError with oddly shaped "g-recaptcha-response" params

### ISSUE THREAD

**Issue by docstun** [ambethia/recaptcha#387]
Hi there,

I investigated some server errors and found exceptions coming from Recaptcha `TypeError: no implicit conversion from nil to integer`

    gems/recaptcha-5.3.0/lib/recaptcha/adapters/controller_methods.rb:80:in `recaptcha_response_token': no implicit conversion from nil to integer (TypeError)
    from gems/recaptcha-5.3.0/lib/recaptcha/adapters/controller_methods.rb:16:in `verify_recaptcha'

The `g-recaptcha-response` param looks suspicious and seems to be submitted by a spammer:

    ...
    "g-recaptcha-response": [
      "\n                "
    ],
    ...

I think it would be great if Recaptcha would handle this and sanitize the param if it's an (empty) array with Recaptcha v2.

I am using Recaptcha v2 with gem version 5.3.0 but I believe this is still an issue in 5.7.0

**Comment by grosser** [comment]
PR welcome, should be fairly simple to add this
