### ISSUE TITLE
Throw an error in verify_recaptcha if recaptcha_reply is empty?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [ambethia/recaptcha#388]
I recently discovered a very unpleasant surprise in an app: in production, I'd misconfigured the site key in our secrets so that a `verify_recaptcha` call started returning `true` all the time. `recaptcha_reply` is `nil` when you debug through it locally. This was very surprising: you'd think the app should fail fast if the call to reCAPTCHA servers is misconfigured / fails, no?

Proposal: can we at least add an optional flag like `fail_fast` to make sure that happens, and recommend its usage? Then default it to `true` in some future breaking change version?

**Comment by grosser** [comment]
the key was empty ? ... that should be easy to make it fail, worst-case we break some dev/test setup

**Comment by JoshuaKGoldberg** [comment]
Closing out my old issues for repos I no longer have context on. If anybody has a need for what this issue was asking about, I'd encourage them/you to file a new issue. Cheers!
