### ISSUE TITLE
Support for recaptcha enterprise?

### ISSUE THREAD

**Issue by dgorelik** [ambethia/recaptcha#390]
Hi, 

Recaptcha enterprise uses `grecaptcha.enterprise.execute()` instead of `grecaptcha.execute()`. In this gem,  it's hard-coded to call `grecaptcha.execute()` https://github.com/ambethia/recaptcha/blob/8fd0ee1c6cd34810f55278b2aa2ddee0fd43483c/lib/recaptcha/helpers.rb#L189.

Is Enterprise support on the roadmap?

Thanks!
Danny

**Comment by grosser** [comment]
no, but PR welcome
