### ISSUE TITLE
g-recaptcha-response-data got empty value on the first time load on 5.8.1

### ISSUE THREAD

**Issue by yusupadik** [ambethia/recaptcha#396]
Hi guys

So I create new apps using gem recaptcha 5.8.1

but on my login form, I got g-recaptcha-response-data hidden field with nil value on the FIRST load, so if I put the wrong password or email, it will give reCAPTCHA verification failed instead of credential failed.
But after I refresh the page, the value becomes exist and got the correct error message

first time load:
![Screenshot from 2021-07-13 11-07-16](https://user-images.githubusercontent.com/1691401/125389280-2c896480-e3cb-11eb-96a9-0df98c058f19.png)

after refresh:
![Screenshot from 2021-07-13 11-12-37](https://user-images.githubusercontent.com/1691401/125389349-46c34280-e3cb-11eb-9cdf-fba8797cd2c9.png)

I call the recaptcha tag using this syntax: 
`<%= recaptcha_v3  action: 'sign_in' %>`

on the controller I do this:
`verify_recaptcha(action: 'sign_in', minimum_score: DEFAULT_RECAPTCHA_SCORE)`

is there anything that I missed?
Thank you

**Comment by grosser** [comment]
if it's just a refresh and not a submit it could be js load speed issue
if it's filled after a submit then it could be from recaptcha setting some vars when validation fails

**Comment by yusupadik** [comment]
yeah, you right @grosser 
it's because js load issue, thanks for the hint, I'll close this issue
