### ISSUE TITLE
Enterprise version

### ISSUE THREAD

**Issue by Asandolo** [ambethia/recaptcha#406]
Hello I want to use enterprise versio so i put the configuration as ask 

```ruby
Recaptcha.configure do |config|
  # config.site_key = '-'
  # config.secret_key = '-

  # Uncomment the following line if you are using a proxy server:
  # config.proxy = 'http://myproxy.com.au:8080'

  # Uncomment the following lines if you are using the Enterprise API:
  config.enterprise = true
  config.enterprise_api_key = 'XXXXXXXXXX'
  config.enterprise_project_id = 'PROJECT'
end
``` 

I have have a an error told me I haven't `site_key` but enterprise configuration don't give me one 

Thank's you

**Comment by grosser** [comment]
Sounds like a bug, try putting enterprise_api_key for site_key and see how that goes. If it works then please report back here or make a PR to fix 👍

**Comment by Asandolo** [comment]
@grosser I test with 
```ruby
Recaptcha.configure do |config|
  config.site_key = 'XXXXXXXXXX'
  # config.secret_key = '-

  # Uncomment the following line if you are using a proxy server:
  # config.proxy = 'http://myproxy.com.au:8080'

  # Uncomment the following lines if you are using the Enterprise API:
  config.enterprise = true
  config.enterprise_api_key = 'XXXXXXXXXX'
  config.enterprise_project_id = 'PROJECT'
end
```

buts not work :/

**Comment by Asandolo** [comment]
I found my error, the enterprise api key must be generated here : 
https://cloud.google.com/recaptcha-enterprise/docs/using-features?hl=fr

**Comment by grosser** [comment]
please make a PR to update the readme if that was unclear :)

**Comment by helmiattastify** [comment]
@Asandolo for site key is it enterprise_api_key?
