### ISSUE TITLE
No proper documentation/ methods for ENTERPRISE version. 

### ISSUE THREAD

**Issue by nitesh-kreditz** [ambethia/recaptcha#429]
Hi 
there is proper methods and documentation for V2 and V3 but it seems there are no methods define for ENTERPRISE version.

@ambethia  @grosser

**Comment by grosser** [comment]
Please search the prs that added the feature and make a PR with what you
can find. If it's unclear you can try asked Ng the original contributors
too.

**Comment by nitesh-kreditz** [comment]
@ambethia @grosser searched PRs but don't find anything which have implemented enterprise version. Also if I add keys mentioned for enterprise then it give `SITE_KEY` not found error.

export RECAPTCHA_ENTERPRISE            = 'true'
export RECAPTCHA_ENTERPRISE_API_KEY    = 'AIzvFyE3TU-g4K_Kozr9F1smEzZSGBVOfLKyupA'
export RECAPTCHA_ENTERPRISE_PROJECT_ID = 'my-project'

**Comment by victor-fdez** [comment]
Hey @nitesh-kreditz,

I hope this helps, though I'm not entirely sure about the specifics of your situation.

For both legacy and enterprise setups, you'll need a `RECAPTCHA_SITE_KEY`. This is typically provided by Google Cloud.

You can obtain the API and Project ID keys when you're retrieving API keys from Google. In summary, you should have these four environment variables set up:

```bash
RECAPTCHA_ENTERPRISE=true
RECAPTCHA_ENTERPRISE_API_KEY=AIzXXXXXXXXXXXXXXXXXXXXXXXXX
RECAPTCHA_ENTERPRISE_PROJECT_ID=project-name
RECAPTCHA_SITE_KEY=6LcXXXXXXXXXXXXXXXXXXXXXXX
```

Key ```RECAPTCHA_SECRET_KEY```  is used in the backend to verify with recaptcha when enterprise is not setup, it's my understanding.

**Comment by victor-fdez** [comment]
@nitesh-kreditz do you think it would have been useful for you to see something on the ```README.md``` that expressed this better?

**Comment by nitesh-kreditz** [comment]
@victor-fdez Just upgraded my old keys to enterprise and it's worked. Thank you!
