### ISSUE TITLE
id on textarea causes duplicate ids if recaptcha_tags is called twice on the same page

### ISSUE THREAD

**Issue by jcoyne** [ambethia/recaptcha#439]
Our automated accessibility check is giving a warning about this.
https://github.com/ambethia/recaptcha/blob/master/lib/recaptcha/helpers.rb#L77

Could that ID be derived from `options[:id]` if present?

Is there a reason that element needs an id?

**Comment by grosser** [comment]
check the id is not used in the js ... if that's the case PR welcome to make it unique

**Comment by grosser** [comment]
then it should be fine
