### ISSUE TITLE
reCaptcha with v2 fallback not showing up when in production

### ISSUE THREAD

**Issue by sectasy0** [ambethia/recaptcha#448]
Hello everyone, I am running applications on production on DigitalOcean and saw that the captcha v2 box does not display in case v3 does not verify, locally everything works, in addition in the resulting HTML on the page script is commented out, why?

Local app running in prod env
![image](https://github.com/ambethia/recaptcha/assets/64311472/dae447ee-9e18-4a6a-8c83-9adb4a2c32df)

Prod env on DigitalOcean:
![image](https://github.com/ambethia/recaptcha/assets/64311472/91ac8bd6-a0bd-43b2-a441-7cf45359d711)

**Comment by grosser** [comment]
no idea, but you can:
- check other issues for similar problems
- check code for where it uses `<!--` and see if that might be triggered

**Comment by sectasy0** [comment]
The issue was resolved by disabling CloudFlare Rocket Loader.
