### ISSUE TITLE
verify_recaptcha() always return false

### ISSUE THREAD

**Issue by AndreyTeslenko** [ambethia/recaptcha#73]
"config/environment.rb"

ENV['RECAPTCHA_PUBLIC_KEY']  = '6LdCbtQSAAAAAL28'
ENV['RECAPTCHA_PRIVATE_KEY'] = '6LdCbtQSAAAAAP'

view:
<%= form_tag params.merge(:action=>"create") do %>
                <div class='block'>
                  <%= text_field_tag 'telephone',nil, :id => "tel"%>  
                </div>
                <div class='overlay-ph'>Введите код с картинки
                 <div class='block' id='capblok'>
                   <%= recaptcha_tags   :display => {:theme => 'white'}%>
                 </div>
                </div>
                <div class='overlay-bt' align='center'>
                <%= submit_tag "Бронировать" %>
                </div>
                <% end %>
controller: 
          @booking = Booking.build(booking)
          if verify_recaptcha() 
            @booking.save
            respond_with(@booking)
          else
            redirect_to :action => "new", :parking_id => params[:booking_step]['parking_id']
         end
gemfile:
    gem "recaptcha", :require => "recaptcha/rails"

problem:
verify_recaptcha()  always returns false. Help me find a bug in the code.
thanks for the earlier.

**Comment by ziedbargaoui** [comment]
Same problem for me, on local environment it's working fine but on staging it's failing.
Does anyone have an idea why ?

**Comment by jedrekdomanski** [comment]
I have similar issue, it works fine in `development`, `staging` and `production` and always retuns `false`in `test` environment.

**Comment by jedrekdomanski** [comment]
The best way to solve this is to just stub `verify_recaptcha`

```
before do
  allow(controller).to receive(:verify_recaptcha).and_return(true)
end
```
