### ISSUE TITLE
Rails 4 integration

### ISSUE THREAD

**Issue by bismark64** [ambethia/recaptcha#83]
I'm using the reCaptcha gem in my Rails 4 app, and the tag for recaptcha isn't displaying, after reloading the page it renders correctly but I suspect that this is caused for the way Turbolinks works in Rails 4 apps..
Have thought about in update the gem to be compatible with Rails4 apps?
How can I do to avoid this? 
Thanks!

**Comment by slehmann36** [comment]
Experiencing this issue now in a Rails 5.2 implementation (with Turbolinks). I'm using reCAPTCHA v3, however, parsing the `ajax: true` argument to the `recaptcha_v3` method has no effect, and doesn't seem to be included in the table of available arguments under the [`recaptcha_v3` heading of the README](https://github.com/ambethia/recaptcha#recaptcha_v3). Is there a solution for this issue that will work for reCAPCTHA v3 implementation? Thanks

**Comment by grosser** [comment]
please make a PR if you find a solution ... best start with `bundle open recaptcha` and debug from there
