### ISSUE TITLE
Thread safety issue

### ISSUE THREAD

**Issue by Bertg** [ambethia/recaptcha#84]
The code used at https://github.com/ambethia/recaptcha/blob/master/lib/recaptcha.rb#L30 is not thread safe.

The `with_configuration` method is modifying the globaly available `Recaptcha::@configuration` variable; which will cause issues.

I would advise either of this two:

- removing this functionality and only rely on inline overrides
- or making `Recaptcha.confguration` and `Recaptcha.with_configuration` thread based; using an other immutable variable for the process defaults.

**Comment by grosser** [comment]
please open a PR
