### ISSUE TITLE
Errors in verify.rb (Using Sinatra)

### ISSUE THREAD

**Issue by ssic7i** [ambethia/recaptcha#85]
In my sinatra application recapcha gem return some errors:
1) undefined method `remote_ip' for #<Sinatra::Request:0x7fdc7e4f8820>
    file: verify.rb
    location: verify_recaptcha
    line: 30
I solve this by change in verify.rb request.remote_ip to request.ip

2) undefined local variable or method `flash' for #<MyServer:0x7f9ac350e0c8>
    file: verify.rb
    location: verify_recaptcha
    line: 55
This error i solved by adding flash = [] before "unless answer == 'true'"
But if i write correct capcha all works fine, if i wrote wrong answer i got errors like Symbol as array index in line 38 of verify.rb or error about converting symbon to integer. I commented all in unless-else-end exept "return true" and "return false". When i do that - check of capcha retun error or pass from my app.

My test application: https://github.com/ssic7i/samples-here/blob/master/test_http.rb
My view for test application: https://github.com/ssic7i/samples-here/blob/master/check.erb

**Comment by grosser** [comment]
please open a PR ... ideally with tests on sinatra
