### ISSUE TITLE
Recaptcha::RecaptchaError (IP spoofing attack?!HTTP_CLIENT_IP="ip1"HTTP_X_FORWARDED_FOR="ip1, ip2"):

### ISSUE THREAD

**Issue by DonGiulio** [ambethia/recaptcha#92]
hello, 

Some of my users (who access from behind a proxy), cannot access the site, and in the logs I see this exception: 

    Recaptcha::RecaptchaError (IP spoofing attack?!HTTP_CLIENT_IP="24.25.26.27"HTTP_X_FORWARDED_FOR="24.25.26.27, 31.32.33.34"):
       app/controllers/registrations_controller.rb:3:in `create'

in my registrations_controller I have: 

    class RegistrationsController < Devise::RegistrationsController
      def create
        binding.pry
        if verify_recaptcha
          super
        else
          build_resource(sign_up_params)
          clean_up_passwords(resource)
          flash.now[:alert] = "There was an error with the recaptcha code below. Please re-enter the code."      
          flash.delete :recaptcha_error
          render :new
        end
      end
    end

line 3 contains the `verify_recaptcha` call. 

any idea on what could cause this? 

thanks.

**Comment by grosser** [comment]
don't think that's recaptcha specific ...
